### ISSUE TITLE
:GoTest errors appear in location list

### ISSUE THREAD

**Issue by myitcv** [fatih/vim-go#1019]
### Actual behavior

`:GoTest` uses the location list for compile errors
### Expected behavior

`:GoTest` should use quickfix for compile errors

Per [the docs](https://github.com/fatih/vim-go/blob/d9c531fca612beb4d4edaa3b4e4efb8c4f5b2cbe/doc/vim-go.txt#L346-L348)
### Steps to reproduce:

```
cd `mktemp -d`
cat <<EOD > main.go
package main

func // this will not compile
EOD
go test
```

You should see the output:

```
./main.go:4: syntax error: unexpected EOF, expecting name or (
```

Open `main.go` in Neovim, the `:GoTest`

Observe that the location list is used
### Configuration
- `vimrc` you used to reproduce: basic `.config/nvim/init.vim` that loads `vim-go`
- vim version: NVIM v0.1.5-752-gfb98145
- vim-go version: a4ba0a5b1b619bfd0b41618620eed1fe6a22a0a2
- go version: go version go1.7 linux/amd64

**Comment by fatih** [comment]
Hi @myitcv 

Seems like for normal vim we still use `quickfix` but it's [hardcoded](https://github.com/fatih/vim-go/blob/master/autoload/go/jobcontrol.vim#L152) for Neovim because we're using jobcontrol. 

To fix it I have to refactor the `Spawn` functions to accept an option argument so I can modify it. For now you can use the following to override it globally until it's fixed for the Neovim case:

```
let g:go_list_type = "quickfix"
```

**Comment by myitcv** [comment]
Thanks for the suggestion of a workaround for now @fatih
