### ISSUE TITLE
:GoCallers uses old $GOROOT

### ISSUE THREAD

**Issue by andrejvanderzee** [fatih/vim-go#1043]
After updating go from Ubuntu package to latest manual download, :GoCallers gives me a long list of the following errors:

```
vim-go: /home/andrej/go/src/github.com/gorilla/context/context.go:8:2: could not import net/http (cannot find packag
e "net/http" in any of:
        /usr/lib/go-1.6/src/net/http (from $GOROOT)
        /home/andrej/go/src/net/http (from $GOPATH))
/home/andrej/go/src/github.com/gorilla/context/context.go:9:2: could not import sync (cannot find package "sync" in 
any of:
        /usr/lib/go-1.6/src/sync (from $GOROOT)
        /home/andrej/go/src/sync (from $GOPATH))
/home/andrej/go/src/github.com/gorilla/context/context.go:10:2: could not import time (cannot find package "time" in
 any of:
        /usr/lib/go-1.6/src/time (from $GOROOT)
        /home/andrej/go/src/time (from $GOPATH))
```

The GOROOT is the old Ubuntu one.

The correct one is:

```
$ go env GOROOT
/usr/local/go
```

**Comment by nhooyr** [comment]
Try `:GoUpdateBinaries`

**Comment by fatih** [comment]
Hi @andrejvanderzee 

Guru embeds the `goroot` into it's library. That's why as @nhooyr said you have to upgrade your binary. We have an open PR to avoid such problems in the future, though that is an improvement that vim-go provides, but the problem is still a user-facing one. Feel free to reopen another issue if it's not getting fixed.

**Comment by andrejvanderzee** [comment]
@nhooyr @fatih That worked indeed! 

And thanks for vim-go too, it's great :-)
