### ISSUE TITLE
Option for autocreate to treat empty directories as a package named after that directory

### ISSUE THREAD

**Issue by jimmyfrasche** [fatih/vim-go#1053]
I love opening a new file and having the package name filled in. 

I don't have much use for the default template, though. I set it to an empty file. 

It would be nice if there were an option so that opening a new go file in an empty directory caused the buffer to contain "package d", where d is the name of the directory.

I'd have to change it if I were writing a command, but more often than not it would be the correct action, at least in my case.

**Comment by fatih** [comment]
Hi @jimmyfrasche 

If you feel adventerous and want to learn some vimscript (and also contribute to vim-go), the code is here: https://github.com/fatih/vim-go/blob/master/autoload/go/template.vim#L19

You can easily add a new setting, such as `go_template_no_file` which is added to line `14`. So we would check first if `go_template_no_file` is set to `1` or if `l:package_name` is `-1`. Because `go_template_no_file` would come first, the else branch will be executed, which in return does what you want, basically creating a file with the package name.

**Comment by jimmyfrasche** [comment]
Thanks for taking the time to lay that out, @fatih.

I've managed to cobble something together after much googling. I'll do some tests locally and try to send a PR tomorrow
