### ISSUE TITLE
Branching strategy Vim 8.0 / neovim

### ISSUE THREAD

**Issue by josefcs** [fatih/vim-go#1063]
I did not find any documentation on this, sorry if it is a duplicate question.

I know that neovim is not a first-class citizen, but it might be of interest for all neovim users.

Looking at issue #1058 , for example made me think, of how will the vim 8.0 branch be compatible with neovim? Are neovim users stuck to the master branch?

I was wondering, because it seems neovim implements a few features from vim 8 already (e.g. json_de/encode, https://github.com/neovim/neovim/pull/4131) but others (like job control) are not implemented.

Thanks,
Josef

**Comment by fatih** [comment]
Hi @josefcs 

That feature is also fixed for nvim, because they both have the same function signature, so no problem there. Even though the branch name is `vim-8.0`, that particular problem is fixed for both platforms.

vim-8.0 will be merged to master, so everyone is stuck to master. With vim-8.0, most of the features that we had already for neovim is now also ported to vim. So actually vim users will benefit from the features you had already for months.

However as a I said earlier and anywhere else, going forward I'm not much interested to invest to maintain both vim and nvim. I just don't have that much time. However again, as I said I'm more than happy to accept bug fixes and improvements from other maintainers/collaborators. 

Thanks
