### ISSUE TITLE
Saving a file with goimports does not preserve correct cursor position

### ISSUE THREAD

**Issue by KevinSjoberg** [fatih/vim-go#1071]
### Actual behavior

When `let g:go_fmt_command='goimports'` is set and I save file that will either append or remove a import statement the cursor position isn't preserved. The position is shifted either up or down depending on what `goimports` added/removed.
### Expected behavior

When saving a file with `let g:go_fmt_command='goimports'` set, I expected the cursor position to stay on the actual line I was on not going back to the same line number.
### Steps to reproduce:
1. Set `let g:go_fmt_command='goimports'`
2. Add a `fmt.Println()` statement into an empty package file
3. Save the file
### Configuration
- vim version: NVIM 0.1.5
- vim-go version: master (commit 8faedbeb)
- go version: go version go1.7.1 darwin/amd64

**Comment by fatih** [comment]
Hi @KevinSjoberg 

We actually restore the cursor position. If you look carefully, you'll see that the cursor is still in the same line (for example `10`), but because `goimports` added new imports the whole file has shifted. I think it's a very minor problem and only appears if there is a new import. To fix your problem, we have to take the `diff` of `goimports` and then compute the additional `lines` and then fix the cursor repositioning. This is a complex bug fix for a small issue. I'm not thinking to add something due to complexity it will bring to the code base. Thanks for opening and giving feedback.

**Comment by KevinSjoberg** [comment]
@fatih thanks for your input. If in the future this would be more feasible to implement, I'd think it's worth another shot. Visual Studio Code does solve this and if I recall, Atom as well.
