### ISSUE TITLE
GoImpl should not create method stubs if they are already implemented

### ISSUE THREAD

**Issue by tobstarr** [fatih/vim-go#1076]
GoImpl should not create method stubs if they are already implemented

**Comment by fatih** [comment]
Hi @tobstarr 

Can you please add more info about this? I remember we talked about this in DotGo but right now the issue lacks context and I don't know anything. Thanks.

**Comment by tobstarr** [comment]
Calling `GoImpl io.ReadCloser` on e.g. this adds the Read method a second time:

```
type User struct {
}

func (u *User) Read(p []byte) (n int, err error) {
    panic("not implemented")
}
```

**Comment by andrewstuart** [comment]
I'm working on a fix for both this and #1077 that involves an upstream change to parse the AST a bit more to determine:
- Which methods are already implemented
- Where the end of the type declaration is so that code can be inserted there automatically.

Also, it should accept a position to write and whether or not to actually update the file. Hopefully an extra-powerful update for the impl tool, and useful for these features as well.

**Comment by fatih** [comment]
@andrewstuart thanks for the comment. If you do the contribution, be sure you add flags to change the way and it's easily executable within vim. Looking forward to it 👍

**Comment by andrewstuart** [comment]
I've gotten a branch of both projects (impl and vim-go) working together. I'm not sure if I should wait until upstream is ready to merge my PR, or if I should just go ahead and submit an interim PR here to make sure the code can be reviewed here in parallel.

The upstream PR is at josharian/impl#16

**Comment by Carpetsmoker** [comment]
I think this is an issue in the upstream `impl` repo? If that is updated it will also work in vim-go without any modifications on vim-go's end?

Is there value in keeping an issue open for it?
