### ISSUE TITLE
Hint on save "Press ENTER or type command to continue"

### ISSUE THREAD

**Issue by guileen** [fatih/vim-go#1081]
### Actual behavior

When I save go files with goimport, vim hint "Press ENTER or type command to continue"， then  I press enter to continue.
### Expected behavior

When I save go files without any error, should not retype "ENTER"
### Configuration
- `let g:go_fmt_command = "goimports"`
- vim version: 7.4, mac OS X
- vim-go   1f8e10cebdacfd7a6809741a9eb04b5e1c3bc6ec  (v1.9+  2016-10-04)
- go version  1.7

**Comment by fatih** [comment]
Hi @guileen 

Did you try this with simple virmc? For me it doesn't say that. I wonder if you do something different?

**Comment by gorsuch** [comment]
hi @guileen -- I had the same issue and resolved it with `go get -u golang.org/x/tools/cmd/goimports`.  Maybe the same will work for you?

**Comment by bdesemb** [comment]
I have the same issue. I tried `goimports` and `goreturns`. I also tried `MacVim` and `Vim`.
Vim version: 8.0 with lua
vim-go: 1.9
Go: 1.7.3
OS: macOS Sierra

**Comment by guileen** [comment]
Not test at a simple vimrc yet.

**Comment by fatih** [comment]
Seems like you have an outdated `goimports`. Please remove all your plugins and update `goimports` and test again. It works out of the box. There is a problem on your end. Thanks.

**Comment by jlukunter** [comment]
I meet the similar problem. I use virtualbox and centOS vm, the host is Windows, shared folder between them. When I save my *.go file in vim on CentOS VM, vim hint "Press ENTER or type command to continue". 
I use 'set cmdheight=4' on my ~/.vimrc and get the error message "could not set security context for main.go".  
That may be some problem happens when virtualbox use the shared folder between Windows and Linux, but the vim-go echo the message.
