### ISSUE TITLE
json snippet only properly works in ultisnips

### ISSUE THREAD

**Issue by nhooyr** [fatih/vim-go#1161]
Compare https://github.com/fatih/vim-go/blob/d7c628ff228c2e6a4d4d5808f198471a775cf8b5/gosnippets/UltiSnips/go.snippets#L187

with https://github.com/fatih/vim-go/blob/d7c628ff228c2e6a4d4d5808f198471a775cf8b5/gosnippets/snippets/go.snip#L160

The neosnippet snippet does not extract the key name.

**Comment by fatih** [comment]
Hi @nhooyr 

Yes, because I don't have the time to add it to neosnippet as well. However I recommend to use `:GoAddTags` as a general usage (Which also supports per line fields). Going forward that would be more useful. Unfortunately I have limited time to tackle things like this. I'm closing this as I want to keep things clean, but I more than happy if you want to tackle and add the feature. I'm open to merge it. Thanks!
