### ISSUE TITLE
expand tab

### ISSUE THREAD

**Issue by vito-c** [fatih/vim-go#1228]
### Behavior
I have expandtab set but the filetype plugin overwrites my settings

### Steps to reproduce:
`set expandtab` in your vimrc

I believe it gets overwritten here:
./vim-go/ftplugin/asm.vim
15:setlocal noexpandtab

./vim-go/ftplugin/go.vim
19:setlocal noexpandtab

expandtab lets you use tab to fill out the spaces. Is there a reason why you had noexpandtab set on the syntax file?

[![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/SsoOG6ZeyUI/0.jpg)](https://www.youtube.com/watch?v=SsoOG6ZeyUI)

**Comment by bhcleek** [comment]
Both gofmt and goimports use tabs for indentation. If you don't want vim-go to auto format Go code, you can `let g:go_fmt_autosave=0` and `let g:go_asmfmt_autosave=0`.

But before you do that, you may want to read https://blog.golang.org/go-fmt-your-code.

**Comment by vito-c** [comment]
@bhcleek I see I didn't realize this was convention from the formatter. Seems like people should be able to control this in their text editor though and then run go fmt via a pre commit hook. I could set up some after plugins to set the expandtab correctly. I guess it's just weird to me that the formatter would prefer tabs to spaces.

**Comment by bhcleek** [comment]
I understand your concern; lots of new gophers experience the same consternation at first. But to quote Rob Pike's Go Proverbs (https://go-proverbs.github.io), "gofmt's style is no one's favorite, yet gofmt's is everyone's favorite."

**Comment by bhcleek** [comment]
You don't need to setup any after plugins, just disable gofmt in your vimrc with `let g:go_fmt_autosave=0`.

**Comment by vito-c** [comment]
but I still want it to format ;D

**Comment by fatih** [comment]
Hi @vito-c 

As @bhcleek said, this is how files are formatted in Go land. vim-go tries to be %100 compatible with the overall Go philosophy. Thanks

**Comment by chew-z** [comment]
I know, I know. We will never have spaces in vim-go since [Elders of the Internet](https://www.youtube.com/watch?v=iDbyYGrswtg) have already ruled on that.

But since [programmers who use spaces earn more](https://stackoverflow.blog/2017/06/15/developers-use-spaces-make-money-use-tabs/), are smarter and better looking there is still a hope.

I have read blog post [Vim can have better tab characters for Golang](https://hashrocket.com/blog/posts/cool-looking-tabs-in-vim) and learned that all you need is one command 
`:set listchars=tab:\|\  ,trail:-,extends:>,precedes:<,nbsp:+`.

**Comment by gun1x** [comment]
Is there anybody working for an option to allow expandtab to work in vim-go?

**Comment by weijunyi** [comment]
I also want an option to allow  expandtab to work in vim-go.
