### ISSUE TITLE
Change in default detection of GOPATH breaks when $GOPATH is a list

### ISSUE THREAD

**Issue by myitcv** [fatih/vim-go#1257]
In 6db12a966ec2ce9be9351621fa5a4ad790b7f623 the default handling of `$GOPATH` was changed:

https://github.com/fatih/vim-go/commit/6db12a966ec2ce9be9351621fa5a4ad790b7f623#diff-827b83031bfe1e9b104191a47bf8c2a7R79

_The use case here is `:GoInfo` incidentally; `go#path#Detect()` is called from [`complete.vim`](https://github.com/fatih/vim-go/blob/6db12a966ec2ce9be9351621fa5a4ad790b7f623/autoload/go/complete.vim#L26)_

Prior to this commit, unless `g:go_autodetect_gopath`was set to `1` (which it is not in my case), then `go#path#Detect()` would return `$GOPATH`. Following this commit, `go#path#Detect()` returns `go#path#Default()` _which is a transformation of `$GOPATH`_.

For setups where `$GOPATH` is a single value, I don't this this change has any effect.

But it breaks setups where `$GOPATH` is set to a list of paths. 

I couldn't see a specific mention of this in the [release notes](https://github.com/fatih/vim-go/blob/master/CHANGELOG.md#112---march-29-2017). 

### Steps to reproduce:

1. Set `$GOPATH` to a list of paths
2. Run `:GoInfo` on a type that you would expect to resolve as valid, and it will show as `invalid type` (because the `GOPATH` passed to `gocode` is now incorrect)

If you insert an `echom` in an appropriate place in `complete.vim` you can see what's going on:

```vim
" complete.vim

...
  " we might hit cache problems, as gocode doesn't handle well different
  " GOPATHS: https://github.com/nsf/gocode/issues/239
  let old_gopath = $GOPATH
  let old_goroot = $GOROOT
  let $GOPATH = go#path#Detect()
  let $GOROOT = go#util#env("goroot")

  echom $GOPATH
...
```

Before 6db12a966ec2ce9be9351621fa5a4ad790b7f623 the output for me is:

```
/home/myitcv/mgo/src/abc.com/g/_vendor:/home/myitcv/mgo
```

(which is correct). Following 6db12a966ec2ce9be9351621fa5a4ad790b7f623 the output for me is:

```
/home/myitcv/mgo/:/home/myitcv/mgo/src/abc.com/g/_vendor
```

which is incorrect and causes `gocode` to return `invalid type`.

### Configuration

No special config required to reproduce this

* `vimrc` plain and simple
* vim version: `NVIM v0.2.0-1171-g4566f7c7`
* vim-go version: 6db12a966ec2ce9be9351621fa5a4ad790b7f623
* go version: `go version go1.8 linux/amd64`
* I'm using https://github.com/mdempsky/gocode as opposed to https://github.com/nsf/gocode

**Comment by myitcv** [comment]
I've updated the description to include the fact that I'm using https://github.com/mdempsky/gocode as opposed to https://github.com/nsf/gocode. I don't think that's relevant however... (unless https://github.com/nsf/gocode relies on this reversing of `GOPATH`?)

**Comment by fatih** [comment]
Hi Paul,

It shouldn't break anything. Let me check that. Probably it's a regression and a side effect of that refactor which I didn't caught on my testing (Because I'm using multiple GOPATH's but all as a single path). Thanks for the feedback, I'll check it and respond back later.

**Comment by myitcv** [comment]
@fatih anything I can do to help on this?

**Comment by fatih** [comment]
@myitcv I was on vacation and abroad for work, so I was derailed. I'll check it

**Comment by fatih** [comment]
@myitcv I've tried to debug this. First of all `:GoInfo` has two modes, `gocode` and `guru`. This should be happen only if you use `gocode` mode (as the problem you describe uses that example, i.e: `let g:go_info_mode = "gocode"`). I've added this to my vimrc. So my `vimrc` has these settings now:

```
let g:go_autodetect_gopath = 0
let g:go_info_mode = "gocode"
```

Also I've changed my `GOPATH` to be a list of paths:

```
$ echo $GOPATH
/Users/fatih/go:/Users/fatih/Code/go
```

When I run within vim the following I can see that my GOPATH is correct:

```
:!echo $GOPATH
/Users/fatih/go:/Users/fatih/Code/go
```

With these changes, I've also added your debug statement (i.e: `echom $GOPATH`). When I now call `:GoInfo` on any identifier, it only returns the first item from the list of GOPATH's. This is what I get:

```
/Users/fatih/go
```

The reason is the line:

```
  let $GOPATH = go#path#Detect()
```

Because autodetect is disabled it'll return here:

```
function! go#path#Detect() abort
  let gopath = go#path#Default()

  " don't lookup for godeps if autodetect is disabled.
  if !get(g:, "go_autodetect_gopath", 1)
    return gopath " <<<------------- WE RETURN HERE---------
  endif

...
```

Which means it returns the output of the `go#path#Default()` output. The function is:

```
function! go#path#Default() abort
  if $GOPATH == ""
    " use default GOPATH via go env
    return go#util#gopath()
  endif

  let go_paths = split($GOPATH, go#util#PathListSep())
  if len(go_paths) == 1
    return $GOPATH
  endif

  return go_paths[0]
endfunction
```

Because I have multiple GOPATH's,  it'll try to split it, if the length is longer than `1`, it'll return the first item from that list. Which is again:

```
/Users/fatih/go
```

Based on this two things I can say is:

1. There is no reshuffling of any kind of items as you see (for my case).
2. Based on the code, we don't return the complete GOPATH anymore (which is a bug). As you see we only return the first item from the list

I'm going to fix the second issue that it should return `GOPATH` unmodified if autodetect is disabled. However I couldn't reproduce the case for shuffling the list of paths. We don't have any code like that in vim-go and I'm not sure how that is happening.

**Comment by fatih** [comment]
@myitcv can you please try https://github.com/fatih/vim-go/pull/1280 and report back? I'm going to merge it and then people can try it until the next release. If there are any other edge cases we're going to fix it. I've tested it locally and it works fine.

**Comment by myitcv** [comment]
@fatih hope you had a good vacation! 

Yes, #1280 does work for me, thanks very much.
