### ISSUE TITLE
Whishlist: TestGoFiles, XTestGoFiles command wrappers

### ISSUE THREAD

**Issue by vbauerster** [fatih/vim-go#1346]
There is `:GoFiles` command which lists the go files. I wish there to be similar commands for listing test files only, something like:
`:GoTestFiles` for `go list -f '{{join .TestGoFiles "\n"}}'`
`:GoXTestFiles` for `go list -f '{{join .XTestGoFiles "\n"}}'`

Default output of such listing commands is not very useful and not very readable. Therefore I propose to integrate such listing commands with [fzf](https://github.com/junegunn/fzf.vim) plugin seamlessly. For example, if fzf is installed, override `:GoFiles` to something like following and if there is no fzf, fallback to default.
```VimL
command! FZFGoFiles call fzf#run(fzf#wrap({
    \ 'source': go#tool#Files(),
    \ 'options': '--preview "(highlight -O ansi {} || cat {}) 2> /dev/null | head -'.&lines.'"'
    \}))
```
(--preview option can be safely omitted)

**Comment by Carpetsmoker** [comment]
I don't think that adding new commands is a good solution since there are 16 filetypes that can be looped over.

Instead, I created a PR to make `go#tool#Files()` and `:GoFiles` accept an argument which specifies which filestypes to list; see #1372.

---

I'm not sure about the fzf integration... This seems like an entirely different thing? I'm not sure how this relates to listing test files etc.

**Comment by vbauerster** [comment]
Sounds reasonable and good! Well integrating with fzf is optional, because who is familiar with fzf, can do integration manually.
