### ISSUE TITLE
go#template#create error when using vim-fugitive :Gdiff

### ISSUE THREAD

**Issue by myitcv** [fatih/vim-go#1399]
### Behavior

See below.

### Steps to reproduce:

* vim-fugitive commit https://github.com/tpope/vim-fugitive/commit/913fff1cea3aa1a08a360a494fa05555e59147f5
* vim-go commit 76cd99db6a88e825f361df0043cbff777c4a14fb
* `NVIM v0.2.1-635-geb40b7ec4`
* `go version go1.9beta2 linux/amd64`

1. Open a `.go` file in a git controlled repo
2. Run `:Gdiff` to view the differences in that file between working tree and staged version
3. See the following error:

```
Error detected while processing function <SNR>45_template_autocreate[3]..go#template#create:
line    6:
E472: Command failed
```

and the side-by-side diff fails to show.

Instead we should see the normal `:Gdiff` output.

This error goes away if `g:go_template_autocreate = 0` (but then so does the templating of new `.go` files)

### Configuration

As above.

**Comment by Carpetsmoker** [comment]
I can't seem to reproduce this; I am using a default Neovim installation (0.2.0, not the latest beta) with just those two plugins in `~/.local/share/nvim/site/pack/plugins/start/` and no further configuration. `:Gdiff` works as expected.

Maybe it's a problem with some specific configuration?

**Comment by Carpetsmoker** [comment]
I'll close this for now due to lack of feedback. Feel free to comment if you have further problems or questions and we can reopen this issue.

**Comment by myitcv** [comment]
@Carpetsmoker - apologies, yes I didn't get a chance to dig into this any further.

If it raises its head again I'll certainly dig deeper.

Thanks

**Comment by nathanmalishev** [comment]
Hey there, I seem to experience a similar issue with vim-fugitive & vim-go.
Probably a simple noob error but worth asking.
The plugin works great on all accounts, except for when I :Gdiff, with vim-fugitive i receive a similar error.
Possibly because vim-fugitive, does something with the file path, placing it under `fugitive:///`?

`go env GOROOT fails` - Works literally every place i can find to run the command, terminal, tmux, vim etc

![image](https://user-images.githubusercontent.com/7652207/31590781-2489446a-b262-11e7-9363-4ecde06452fa.png)

**Comment by bhcleek** [comment]
@nathanmalishev I've seen similar issues, but haven't dug into a root cause yet. 

In your case, it looks like you may have `g:go_auto_sameids=1`. If that's the case, then you can work around this issue by calling `:GoSameIdsAutoToggle` to turn off `g:go_auto_sameids` when you have a fugitive window open.

**Comment by nathanmalishev** [comment]
@bhcleek thanks for the quick response. That seems to be the work around!

**Comment by vedharish** [comment]
@Carpetsmoker I can reproduce this as well..
Required - 
1. git repo must be initialised for the file
2. the file currently being edited must be UNTRACKED in git

Point 2. makes sense because the :Gdiff command compares an empty buffer (`filetype=go`) with the whole file and `vim-go` tries to `template_autocreate` on the empty buffer

:Gdiff works fine for me on all git tracked files
