### ISSUE TITLE
GoReference takes a long time to process

### ISSUE THREAD

**Issue by migore** [fatih/vim-go#1410]
### Behavior

GoReference takes a long time to process, it took about 8 seconds to process. Is there some kind of indexing config?

### Steps to reproduce:

Re produce it with a minimal `vimrc` with all plugins disabled and
only `vim-go` enabled:

1. Checkout [Kubernetes](https://github.com/kubernetes/kubernetes) commit 039f898c07a643d6ef244fcb65daff5a53de41c8
2. Go to file plugin/cmd/kube-scheduler/app/configurator.go line 78, CreateScheduler function
3. Run :GoReferrers

Result: It took about 8 seconds to open the options
Expected: Instant, but about a second is good.

### Configuration

* vim version: 8.0.893
* vim-go version: Commit 76cd99d
* go version: 1.8.3

Mac Config:
Processor: 2,5 GHz Intel Core i7
Memory: 16 GB 1600 MHz DDR3

**Comment by fatih** [comment]
Hi @migore 

If you have a large GOPATH that's normal because `guru` (the underlying tool) doesn't have caching so it indexing over and over again. Unfortunately there is not much I can do on my side. You can try to run `guru` from your terminal and also see how it takes. I suggest to open an issue to golang/go repo and ask there. Thanks for the feedback nevertheless.
