### ISSUE TITLE
Inconsistent spacing condition vs variable math

### ISSUE THREAD

**Issue by fanus** [fatih/vim-go#1462]
### Intro
Apologies for the very trivial request. I realise this is most likely more to do with gofmt than this plugin, but could it maybe be configure somehow with vim-go?

### Behaviour
There seems to be an inconsistency in the white spaces when I doing simple math in a condition vs storing a variable value.

A common example of this is seem in the follow code:
```
for a := 0; a < len(c.colliders)-1; a++ {          
        for b := len(c.colliders) - 1; b > a; b-- {
        }                                          
}                                                  
```
vim-go formats the minus one's differently. What I expected is something like this (see first line):

```
for a := 0; a < len(c.colliders) - 1; a++ {          
        for b := len(c.colliders) - 1; b > a; b-- {
        }                                          
}                                                  
```

### Configuration
* vimrc - no configuration
* vim version: VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Aug 26 2017 14:06:38)
* go version: go version go1.9 linux/amd64

**Comment by Carpetsmoker** [comment]
It's how `gofmt` formats code; it's been brought up a bunch of times; see e.g. [this](https://groups.google.com/forum/#!topic/golang-nuts/PbJ1uTbhFDY) and [this](https://github.com/golang/go/blob/master/src/go/printer/nodes.go#L598).

> could it maybe be configure somehow with vim-go?

The entire point of gofmt is to stop discussions about code formatting and where to put spaces and whatnot in the entire Go community ;-)

The particular style it chooses it no one's favourite, but because of its consistency and easy-of-use it's also everyone's favourite ;-)
