### ISSUE TITLE
Better reformatting for comments

### ISSUE THREAD

**Issue by ncdc** [fatih/vim-go#1508]
### Behavior

I use `vipgq` to reformat a "paragraph" of text - typically a multiline comment. This works fine if there is at least 1 blank line above and below the paragraph. If there is go code immediately adjacent, the resulting formatted text is messed up.

### Steps to reproduce:

1. Write something like this:
```go
func main() {
        // Line 1.
        // Line 2.
        // Line 3.
        x := 0
}
```
2. Put the cursor on one of the comment lines
3. Type `vipgq` to select the paragraph and reformat it

Result:
```go
func main() {
        // Line 1.  Line 2.  Line 3.
        x := 0 }

```

### Configuration

Add here your current configuration and additional information that might be
useful, such as:

* `vimrc` you used to reproduce
```
set nocompatible
call plug#begin('~/.vim/plugged')
Plug 'fatih/vim-go', {'tag': '*'}
call plug#end()
```
* vim version: 8.0.1100_1
* vim-go version: v1.13
* go version: 1.9

**Comment by ncdc** [comment]
Note, I frequently want to reformat both comments about specific blocks of code, as well as godoc comments above a function declaration. What I'm really looking for is "from the current cursor position, find the beginning and end of the (possibly multiline) comment, and reformat it." And this should be for both `//` and `/* */` style comments if possible.

If there's anything I can do to help implement this, a gentle pointer would be appreciated & I can see about helping out.

**Comment by Carpetsmoker** [comment]
Wrapping comments like that is a feature, in my opinion, and also how most languages behave (C, Python, and Ruby do, anyway). Is there any filetype that you know of that behaves different?

In the specific case of Go I would use `gofmt` (`:GoFmt`) by the way, is there any reason in particular you're using `gq` instead of `gofmt`?

---

For example, I often edit existing comments which results in something "jagged" like:

```
// This is one
// sentence and it will continue
// here.
```

the reason it ends up like this is because there was more text before.

If I reformat it, it ends up as a single line:

    // This is one sentence and it will continue here.

which is exactly what I'm looking for.

I'm not sure how to support both use cases?

**Comment by Carpetsmoker** [comment]
I think that setting `equalprg` to run `gofmt` would be a good solution, then you can use `vip=`. What do you think?

**Comment by bhcleek** [comment]
Instead of `vipgq`, do `gq}` or `ipgq`, and I think you'll get the result you're looking for.

Also notice that visual mode (e.g.`vipgq`) shows you exactly which lines it's going to format with `gq` before those keys are entered. If `ip` isn't the right selection, then use `k` to go up to the last line that you want to have formatted.

**Comment by ncdc** [comment]
@Carpetsmoker what I'm really looking for is to be able to reformat a multiline comment according to my `textwidth` setting. I don't think that's something that `gofmt` can handle (or can it?). When I tried your "jagged" example, I couldn't get `:GoFmt` to change it from 3 lines to 1.

@bhcleek both `gq}` and `gqip` are too aggressive, resulting in the closing brace on the wrong line (here's the result again, for reference):
```go
func main() {
        // Line 1.  Line 2.  Line 3.
        x := 0 }
```
If I then save (which runs `goimports`), it does move the brace to the correct location, on a line by itself. Maybe I could live with that, but I'm hoping there's a way to identify contiguous comment lines  instead.

Also, I have `vipgq` mapped to `<leader>rf` (for **r**e**f**ormat), so I'm not actually interacting with the visual selection.

I appreciate the feedback! If there is some automated key combination that will select contiguous comment lines, I'd love to hear about it 😄 .

**Comment by bhcleek** [comment]
For multi-line comments, `[/gq]/` seems to do exactly what you want.

I did find that `gq][`  mostly does what you what you want, but doesn't backtrack to the first in the set of comments.

You could also consider mapping `<leader>rf` to `vipgq:GoFmt` so that the curly brace gets put back to to its own line.

I think we could add something like a mapping to https://github.com/fatih/vim-go/blob/master/ftplugin/go.vim that could backtrack to the first comment line and then format it it. It would probably be easiest to:
1. backtrack to the first comment line
2. strip the leading `//` in the block of comments
3. prefix and suffix the block with `/*` and `*/`, respectively.
4. run `[/gq]/`
5. remove the `/*` and `*/` and prepend each line with `//` again.

Do you have any interest in contributing that?

**Comment by ncdc** [comment]
@bhcleek thanks for the info, I'll check out your suggestions. As to contributing, I'd be happy to... but my vimscript knowledge is about as basic as it gets. If you have any pointers for how to do items 1-5 in your list above, I'd appreciate it.

**Comment by Carpetsmoker** [comment]
Oh, right. The formatting behaviour is correct, you just want some way of selecting just the comment block. Guess I misunderstood your issue.
