### ISSUE TITLE
How can I find the definition of the function under TestType use vim-go.

### ISSUE THREAD

**Issue by widon1104** [fatih/vim-go#1545]
### What did you do? (required. The issue will be **closed** when not provided.)

Please provide a recipe to replicate your problem with a minimal `vimrc` with all plugins other than vim-go disabled.

### What did you expect to happen?
In code beblow how can I find the definition of sayhello under TestType.  I use ctrl+] can only find the definition under TestInterface, but what I want is func (*TestType) sayhello() . So I can only grep to find it, it's very inconvenient.vim-go can help me to find it ? thanks.
node: if I use c or c++, I can use gnu global to generate tags for vim which can help me find the place where a function call, but gnu global do not support golang, so I can only use grep all the time now...

```
//×××××××××××××××××××××××××
package main

import "fmt"

type TestType struct {
	Val int
}

func (*TestType) sayhello() {
	fmt.Println("hello")
}

type TestInterface interface {
	sayhello()
}

func main() {
	t := new(TestType)
	var i TestInterface
	i = t
	i.sayhello()
}
//×××××××××××××××××××××
```

### Configuration

* vim version (major, minor, and included patches from `:version`):  vim 7.4
* vim-go version:  latest
* go version (`go version`): 1.9
* operating system: ubuntu 16.04 mate
* `vimrc` you used to reproduce: do not need it.

**Comment by Carpetsmoker** [comment]
There isn't really any way to do that, because the method definition on the interface *is* the definition for your `TestInterface` type.

For example, what if the code looked like this:

```
func main() {
	t := new(TestType)
	var i TestInterface

       if randomNumber() > 2 {
	    i = new(TestType)
        } else {
            i  = new(OtherType)
        }
	i.sayhello()
}
```

Now there is no way any program can determine to which concrete implementation of `sayHello` we should jump to. In contrived examples such as your it's "easy" to see that this is really `TestType`, but in almost all real-world examples an interface can point to two or more concrete types, and it's not easy to see which one it "really" is: it depends on the function caller, outside input, etc.

The entire point of interfaces is to abstract code like this, so that you can use any number of concrete types. For better or worse, I don't see a way to do this better. I agree it can be annoying though.

That being said, you can use `:GoImplements` to see what implements something, which is often helpful.

**Comment by bhcleek** [comment]
`guru` helps with this. Try placing the cursor on the `sayHello` in `i.sayHello()` and then execute `:GoCallees`.

**Comment by widon1104** [comment]
widon@widon-desktop:~/go/src$ pwd
/home/widon/go/src
widon@widon-desktop:~/go/src$ echo $GOPATH
/home/widon/go:/home/widon/uCloudChain:/home/widon/uCloudChain/src/vendor
but when I execute :GoCallees on sayHello, error print out
vim-go: current directory is not inside of a valid GOPATH

**Comment by bhcleek** [comment]
What do you get for `:echo $PWD` inside of vim after trying `:GoCallees`?

**Comment by widon1104** [comment]
:echo $PWD
/home/widon/go/src

**Comment by widon1104** [comment]
I find out I must mkdir a new folder, and put my code into that folder to make :GoCallees work..
this is a bug...

**Comment by bhcleek** [comment]
It's neither a bug in vim-go, guru, nor go.

https://golang.org/cmd/go/#hdr-GOPATH_environment_variable
