### ISSUE TITLE
How do we want to install gometalinter tools?

### ISSUE THREAD

**Issue by Carpetsmoker** [fatih/vim-go#1555]
Right now only a few are installed by default (e.g. errcheck etc.), but most aren't.

The gometalinter repo comes with the tools in the vendor directory, and `gometalinter --install` just `go install`s it from there, so running this is pretty fast and doesn't download anything.

Also see: #1530, #1552

**Comment by fatih** [comment]
What about a command like `:GoMetaLinterInstall` which kinda does the installation? Also seems like `go vet` now accepts all arguments that `go tool vet` also accepts, which means that people using `:GoMetaLinter` don't have to install the tools to make gometalinter to work: https://groups.google.com/forum/#!msg/golang-dev/qfa3mHN4ZPA/X2UzjNV1BAAJ

**Comment by bhcleek** [comment]
`gometalinter --help` claims that `--install` is deprecated. The release notes for https://github.com/alecthomas/gometalinter/releases/tag/v2.0.0 confirm this:
> Another major change is that from now on we will be releasing binary packages. gometalinter's management of linter installation will soon be deprecated, and eventually removed.

**Comment by docwhat** [comment]
There is an issue on how to [_install the released 2.x tarballs_](https://github.com/alecthomas/gometalinter/issues/418).

**Comment by fatih** [comment]
That's a good plan actually. I think they want people to install the tools themselves or handle the releasing themselves instead of doing our way of installing via `go get. Maybe we should not handle this as well on our side? We already have some default linters (govet, golint, goerrcheck) and for gometalinter it's a valid assumption that people should install the other linters themselves. I'm not sure how long we can sustain catching up with gometalinter on installing linters.
