### ISSUE TITLE
Guru commands don't open quickfix

### ISSUE THREAD

**Issue by riccardofreixo** [fatih/vim-go#1700]
### What did you do? (required. The issue will be **closed** when not provided.)
Following the tutorial here: https://github.com/fatih/vim-go-tutorial#dependencies-and-files
The following commands do not open quickfix:
```
:GoReferrers
:GoDescribe
:GoImplements
:GoWhicherrs
:GoChannelPeers
:GoCallees
```

### What did you expect to happen?
A quickfix list to open.

### What happened instead?
A location list opened instead.

### Configuration (**MUST** fill this out):

* Vim version (first two lines from `:version`):
```
NVIM v0.2.3-776-g3d2f4154b
Build type: Release
```

* Go version (`go version`):
`go version go1.9.4 darwin/amd64`

* Go environment (`go env`):
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/rfreixo/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/mc/7790tl8n35zfllsyt0q6dd6hjhwx43/T/go-build033247645=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

* vim-go version:
eaef6f79323a3df110928020dfc877d26332c80a - latest commit to master.

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
```
" Autoload everything in autoload
for f in split(glob('~/.vim/autoload/*.vim'), '\n')
    exe 'source' f
endfor

" Pathogen
execute pathogen#infect()
```
The only plugin loaded under autoload is pathogen.vim.
The only plugin loaded by pathogen is vim-go.

**Comment by bhcleek** [comment]
This is by design and was changed since the tutorial was written. Please feel free to open an issue in https://github.com/fatih/vim-go-tutorial to document that it needs to be updated.

Guru output is loaded into the locationlist by default, because by definition, the information it's presenting is derived only from a single buffer. Among other things, this will allow a user to view information provided by guru in multiple windows simultaneously. (e.g. you may want to see the output of `:GoReferrers` in both windows of a split).

**Comment by riccardofreixo** [comment]
Thanks @bhcleek, I made a PR to the tutorial to remove references to quick lists from the Guru commands.
