### ISSUE TITLE
Go GoImport on tab

### ISSUE THREAD

**Issue by ldelossa** [fatih/vim-go#1719]
Is it possible (or even a good idea) to get supertab to run "GoImport" before displaying suggestions? This will allow for you to begin typing a library such as "fmt." and hit tab, GoImport will import fmt and the suggestions will fill properly.

**Comment by fatih** [comment]
Hi @ldelossa 

I'm not sure if I've understand this correctly. Do you want to call `:GoImport` in the context of the current cursor? Because currently the command just adds an import path and it already supports completion. It would be helpful if you could provide more information.

**Comment by ldelossa** [comment]
So currently the workflow which inspired this request is the following:

Working on code and get to a line where I begin to type a package name not imported into the code
Stop here and now type "GoImport packge" to import the package
Continue my typing of the entity in the package I was trying to access.

Instead I was thinking it could happen like:

Working on code get to a line where I begin to type a package name not imported
Hit tab syntax completion after typing the ., for example "fmt.<TAB>". At this point have Gofmt run which should see the fmt. string and import the package.
Resume tab completion after gofmt ran and has imported the package for you. 

This avoids the need to stop what are you doing and run GoImport. 

Is this possible ?

**Comment by fatih** [comment]
Hm I see. So when I type `errors.` and hit tab after the dot, it should import `errors` if it's see that `errors` is not imported? Isn't this the same when you use `goimports` ? The problem here is that it's not easy to know wether the identifier is refereeing to a package, is a variable, constant or anything else. This is not easy task on our side. This could be solved via `gocode` though, but it's not implemented yet, see: https://github.com/nsf/gocode/issues/368 

So for now, I recommend to use `goimports` instead of `gofmt` and subscribe to the gocode issue above and see whether `gocode` supports it. Once gocode supports it,it's easier to complete unimported packages. Combined with `goimports` you'll get the workflow what you want. 

I'm closing the issue as there is not much we can do. Thanks for the feedback though.

**Comment by ldelossa** [comment]
Thank you!
