### ISSUE TITLE
Is it possible to highlight line number of line with error (as syntastic)?

### ISSUE THREAD

**Issue by NCSantos** [fatih/vim-go#1727]
Hi,

The title is my question.

Thanks for your help.

**Comment by Carpetsmoker** [comment]
Perhaps? I don't know what syntastic does and what you mean exactly. Did you try reading the documentation?

**Comment by NCSantos** [comment]
If you put the cursor over the line it also shows the error under the statusline.

https://youtu.be/t4FP7tHXtEU?t=11s

**Comment by Carpetsmoker** [comment]
Isn't that just the quickfix/location list? What command did you use?

**Comment by NCSantos** [comment]
I have set syntastic to go build on save.

To the left of line 4 you can see it highlighted, even the place of the error is highlighted, in that case "-".

It's not quickfix or location list.

**Comment by mocheryl** [comment]
>   There is also https://github.com/w0rp/ale for vim8 and nvim

Both ale and syntastic are great projects, but they're very heavy-duty for when you just want some simple syntax highlighting for a single language. That's why I decided for that addition mentioned in my previous comment because it makes things more light-weight and gives almost the same functionality out-of-the-box. I even took a lot of code and concepts from them.

**Comment by fatih** [comment]
There are no plans to add this support to vim-go. As we said many times, there is ALE and Syntastic that gives you the feature. Adding this feature would mean for us to maintain it forever for all upcoming releases and also making sure it always works. Thanks for the feedback.
