### ISSUE TITLE
Test - Re-run the last test

### ISSUE THREAD

**Issue by masch** [fatih/vim-go#1780]
Hi!

I use :GoTestFunc a lot, but it would be wonderful if there is a command to re-run the last test executed like :GoTestLastFunc.
It would be a great feature for TDD methodology, specially when I am doing refactor.

Thanks!

**Comment by Carpetsmoker** [comment]
Or how about `:GoTestFunc last`? I made a PR to do that: #1789

**Comment by mchacon-ml** [comment]
Yeah, that is an excellent feature. Right know I am using janko-m/vim-test pluing, but I lost some feature because it is not integrated with vim-go.
It has another feature like these:

:TestNearest | In a test file runs the test nearest to the cursor, otherwise runs the last nearest test. In test frameworks that don't support line numbers it will polyfill this functionality with regexes.
-- | --
:TestFile | In a test file runs all tests in the current file, otherwise runs the last file tests.
:TestSuite | Runs the whole test suite (if the current file is a test file, runs that framework's test suite, otherwise determines the test framework from the last run test).
:TestLast | Runs the last test.
:TestVisit | Visits the test file from which you last run your tests (useful when you're trying to make a test pass, and you dive deep into application code and close your test buffer to make more space, and once you've made it pass you want to go back to the test file to write more tests).

Thanks for the PR!

**Comment by Carpetsmoker** [comment]
I don't think we should try to re-implement stuff like vim-test. If you want to use vim-test's more advanced features, then use vim-test :-) If Go support isn't up to spec in that for some reason, then it's probably a good idea to open an issue or PR for that.
