### ISSUE TITLE
GoImpl tab complete

### ISSUE THREAD

**Issue by ldelossa** [fatih/vim-go#1867]
### What did you do? (required. The issue will be **closed** when not provided.)
Attempt to tab complete known packages with GoImpl tool. Not quite sure if this is a GoImpl issue or if vim-go implements the directory completion. If GoImpl issue close and I will open issue at that repo. 

### What did you expect to happen?
Autocompletion of package paths in $GOPATH/src

### What happened instead?
No completion

### Configuration (**MUST** fill this out):

* vim-go version:
master
* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
n/a
* Vim version first three lines from `:version`):
NVIM v0.2.2
* Go version (`go version`):
go 1.10.1
* Go environment (`go env`):
❯ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/louis/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/louis/git/go"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/m2/gl_nd53n44vcnjbv49n6_kv40000gn/T/go-build703823739=/tmp/go-build -gno-record-gcc-switches -fno-common"

**Comment by Carpetsmoker** [comment]
vim-go implements this, and it seems to work for me in a quick test. Do you have a specific package/file where it consistently breaks?

**Comment by ldelossa** [comment]
@Carpetsmoker 

So I just made sure I had all latest commits pulled and  tab completion does bring up some options but they seem to be individual package names.

<img width="2545" alt="screen shot 2018-06-21 at 12 04 55 pm" src="https://user-images.githubusercontent.com/5642902/41731040-5c8afd98-754b-11e8-83f7-e7b2576b91b7.png">

What I'm expecting is to begin typing "github.com" and it begin to index what's in $GOPATH/src/github.com/* similar to how the GoImport tool works. 

<img width="2541" alt="screen shot 2018-06-21 at 12 06 06 pm" src="https://user-images.githubusercontent.com/5642902/41731105-85c3564c-754b-11e8-92b9-1ef8d224314a.png">

**Comment by fatih** [comment]
Hi @ldelossa 

Could you try the following PR please: https://github.com/fatih/vim-go/pull/1884

It's really difficult to get this right, however it works %90 of the time if you get used to it. The reason is that we try to get the `inteface` name after a `.` (dot). 

However there are cases, for example such as `github.`, in this case this is part of the import path and not the package yet. Therefore if you try to write `github.` first and try to complete it'll fail, however if you write `g...`, `gi....`, `git...` this will complete to `github.com/` which then you can continue writing. 

Let me know how this works, there is not much I can do here anymore as I think it's not wort spending so much time, but at least it's able to complete packages now in a meaningful way :)

**Comment by ldelossa** [comment]
Thank you @fatih this is much better then before regardless of the expansion issue. Works well
