### ISSUE TITLE
cgo

### ISSUE THREAD

**Issue by porjo** [fatih/vim-go#211]
I'm wondering how best to use vim-go with code that imports C code. 

I find that when I do a build and have, for example, a missing C header file, the compiler will error due to unknown C type. Vim then replaces my Go file with a C header file. I'd prefer it didn't do that, but kept the Go file loaded and just displayed the quickfix window.

**Comment by fatih** [comment]
I'm closing this because CGO errors are not Go errors and needs to be handled outside this plugin. I'm not using CGO, also when you look at how the Go developers seeing CGO as no-go for applications I see no value investing time into something that will be eventually not used much in the future. It'll be 1.5 years and no comment was made to this issue as well, which shows how less this is a concern.  I'm open to include any contributions if someone want's it to tackle. Thanks!
