### ISSUE TITLE
Autocomplete stopped working after 1.20 update

### ISSUE THREAD

**Issue by cpheps** [fatih/vim-go#2242]
### What did you do? (required. The issue will be **closed** when not provided.)
When trying to use auto complete by pressing `<C-X><C-O>`

### What did you expect to happen?
Autocompletion to work

### What happened instead?
Got a 
```
Error detected while processing function go#complete#Complete
line 10:
E117: Unknown function: funcref
```

### Configuration (**MUST** fill this out):

* vim-go version:
1.20

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
```
" Add vim-go
Plugin 'fatih/vim-go'

" Add nerdtree
Plugin 'scrooloose/nerdtree'

" Add nerd commentor
Plugin 'scrooloose/nerdcommenter'

" CtrlP
Plugin 'ctrlpvim/ctrlp.vim'

" Vim Gutter
Plugin 'airblade/vim-gitgutter'

" Light Line
Plugin 'itchyny/lightline.vim'

" Fix starting complaint
let g:go_version_warning = 0
let g:go_fmt_command = "goimports"
let g:go_highlight_function_parameters = 1
let g:go_highlight_fields = 1
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_operators = 1
let g:go_highlight_structs = 1
let g:go_highlight_types = 1
```

.vim/after/ftplugin/go.vim:

```
setlocal omnifunc=go#complete#Complete
```

* Vim version (first three lines from `:version`):
```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 24 2016 16:44:48)
Included patches: 1-1689
Extra patches: 8.0.0056
```

* Go version (`go version`):
```go version go1.11.2 linux/amd64```

* Go environment (`go env`):
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/cphelps/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/cphelps/faas-ws"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build922606035=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by bhcleek** [comment]
There a couple things here:

First, the gopls support won't work for Vim 7.4, because it relies on features that may not be available; you might need to continue using gocode if you don't want to upgrade to Vim8. You can continue using gocode simply by removing the `setlocal omnifunc=go#complete#Complete` in your `.vim/after/ftplugin/go.vim` file; vim-go will use gocode by default with Vim 7.4.

Second, the error you're seeing is because `funcref` was introduced in Vim 7.4.2137, but you're on Vim 7.4.1689. Since vim-go requires at least Vim 7.4.2009, your version isn't supported by vim-go at all.

**Comment by cpheps** [comment]
Cool thanks for following up.
