### ISSUE TITLE
Add Syntax group for the variable type which is a custom struct

### ISSUE THREAD

**Issue by taigacute** [fatih/vim-go#2330]
### What did you do? (required: The issue will be **closed** when not provided)

1. type a new struct
2. defined a variable  and its type is that struct
3. the type of this struct not highlight
![13](https://user-images.githubusercontent.com/41671631/58749808-2e2e9180-84bd-11e9-9519-518f90c48887.png)

### What did you expect to happen?
highlight the `Database` which in  `var database Database`
### What happened instead?
N/A
####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
```VIML
let g:go_fmt_command = "goimports"
let g:go_highlight_types = 1
let g:go_highlight_fields = 1
let g:go_highlight_functions = 1
let g:go_highlight_function_calls = 1
let g:go_highlight_methods = 1
let g:go_highlight_structs = 1
let g:go_highlight_operators = 1
let g:go_highlight_extra_types = 1
let g:go_highlight_build_constraints = 1
let g:go_highlight_generate_tags = 1
"disable use K to run godoc
let g:go_doc_keywordprg_enabled = 0
```

#### Go environment
N/A

**Comment by bhcleek** [comment]
It's difficult to get this right, because it has to be done with regular expressions and would have to highlight the type correctly in all these scenarios (and likely in the short forms, too):

```
type Foo struct{}
type Bar interface{}
type Baz int

var i Foo
var U, V, W Bar
var k = 0
var x, y Baz = -1, -2
var (
	i       Foo
	u, v, s = 2.0, 3.0, "bar"
        j = Baz(k)
)
```

Given the complexity of handling all those situations without breaking any existing syntax highlighting, this is unlikely to be implemented any time soon. I'll give it some more thought, but I'm leaning towards closing this as a won't fix 🤔

**Comment by taigacute** [comment]
Yes, it seems to be difficult to implement, because it may be uppercase or lowercase, and the location is difficult to determine. I checked the vscode emacs and it didn't work. Only goland can display correctly
