### ISSUE TITLE
why add args "--disable-all" 

### ISSUE THREAD

**Issue by Hyvi** [fatih/vim-go#2399]
https://github.com/fatih/vim-go/blob/0a0ded2cbfea03d151ba10c90f074b596c207bba/autoload/go/lint.vim#L276

when i delete the line,  no errors occurs : 
`Running error: --enable-all and --disable-all options must not be combined
`

**Comment by bhcleek** [comment]
I suspect that you have `--enable-all` in your `golangci-lint` config file. vim-go uses `--disable-all` so that only the linters specified in `g:go_metalinter_enabled` will be used. Unfortunately, `golangci-lint` allows you to put `--enable-all` in its config file _and_ doesn't allow that to be overridden on the commandline.
