### ISSUE TITLE
quickfix window does not recognize linting issues as errors

### ISSUE THREAD

**Issue by acgreek** [fatih/vim-go#2416]
If I save my work and there is an error reported from the auto-linter, it would be a major productivity improvement if the curser auto moved to the first error, and :cn moved the next error.

:c* commands does work if I run :GoBuild or :GoTest but it would be nice if it also worked for the auto-linter.

I tried to updated the errorformat variable with the linter syntax, but that didn't work.

**Comment by bhcleek** [comment]
What auto linter are you referring to? vim-go does automatically jump to errors out after linting. Have you set `g:go_jump_to_error`?

As an aside, we provide an issue template so that you can help us diagnose your issue as quickly as possible. Please consider using it instead of deleting it when creating a new issue.

**Comment by acgreek** [comment]
I believe I was using stock EverVim setup (https://github.com/LER0ever/EverVim) at work but experience the same issue with Spf-13 (http://vim.spf13.com/).they both auto-install your vim-go module. 

After installing the go tools binaries via GoInstallBinaries, I close vim and open a new file go file
vim test.go

then I type in the following bad go source
....
package main

func main() {
  fmt.Println("vim-go"
  fmt.Println(l
} 
....
I have my cursor set after the last character of the source
then I save via :w

as a result, I get a nice quickfix like window at the bottom of my shell showing me the error  
  1 test.go|4 col 22| : missing ',' before newline in argument list 
  2 test.go|5 col 15| : missing ',' before newline in argument list
  3 test.go|6 col 1| : expected operand, found '}'

after that window pops up, my curse is still at the last spot I left it (bottom of source) and when I type :n i a get message 

E43: No Errors

and yes I have g:go_jump_to_error set to 1. I verified via :echo g:go_jump_to_error, it returns 1

if I then do :GoBuild, then the curser moves right to the error and :n says no more error (which is accurate given go builds output)

What I would like is for :w to behave like :GoBuild, IE move the curse to the first error listed and let me move through the errors with :n :p

**Comment by bhcleek** [comment]
Thank you for taking the time to explain what you're seeing in more detail. Just to be clear; what you're seeing is not from a linter. It's the output of `gofmt` or `goimports`. Since it applies to only the buffer in the window being saved, it's the location list, not the quickfix list that's populated. You can navigate it by using `:lne` et al. instead of `:cn`.

It doesn't jump to the first error, because that would interrupt the vast majority of people's workflows when they save a file.

**Comment by acgreek** [comment]
thanks
