### ISSUE TITLE
Cannot navigate to next error

### ISSUE THREAD

**Issue by pengux** [fatih/vim-go#247]
Errors in Go files seems to be different and cannot be navigated to by using :cn or :lne. Is there any other way to cycle through all errors in a buffer?

**Comment by elithrar** [comment]
@pengux What was the actual issue with syntastic? How did you correct it?

**Comment by pengux** [comment]
@elithrar I don't remember exactly, but I have these two lines in my .vimrc so maybe you can try it

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1

**Comment by yaojingguo** [comment]
The setup as specified in https://github.com/fatih/vim-go/blob/master/README.md#using-with-syntastic solves this problem.

**Comment by vorstack-jeff** [comment]
Something else is going on... I don't have syntastic and have this same issue. Open to trying things to debug it.

**Comment by hongzhouchen-oceanwing** [comment]
@pengux Thanks for your comment. It solved my problem.

**Comment by blacksails** [comment]
@vorstack-jeff did you get it working? I dont have syntastic and i have the issue aswell.

**Comment by andradei** [comment]
@modood Worked for me. Thank you.

**Comment by bxsx** [comment]
Hi @fatih 

Let me know if I should open a new issue for this but..

I have exactly the same problem. `:cc`, `:cn`, `:lnext` etc. says `No errors`. However it's working fine when first calling `:GoBuild`, but since the lines were highlighted on the fly (without former building or saving file), it would be nice to jump to the next error.. How can I do that?

PS. I don't use `GoMetaLinter` or `Syntastic`, my VIm configuration for Go is very simple:
```vim
let g:go_def_mode='gopls'
let g:go_info_mode='gopls'
```

**Comment by bxsx** [comment]
> PS. I don't use `GoMetaLinter` or `Syntastic`, my VIm configuration for Go is very simple:

Turned out that these errors have been identified by YouCompleteMe. Fixed now :)
