### ISSUE TITLE
Reinitialize gopls

### ISSUE THREAD

**Issue by mnarrell** [fatih/vim-go#2550]
I apologize for opening an issue for this, but I was unsure how to ask a question.

Is there a method for restarting or reinitializing gopls?  Often I get into a state where goals is unhappy, either from switching complex branches, or some error in another package.  I can resolve this by simply restarting vim, but I'd prefer a different approach.

If there is a better way to ask questions to this community, please let me know.

**Comment by bhcleek** [comment]
Thanks for asking the question, @mnarrell. Switching branches without restarting Vim will put you in a bad state with `gopls` right now, but that won't always be true. I definitely recommend exiting Vim before switching branches. However, if you have problems with `gopls` because of some error in a package, please create issue in https://github.com/golang/go/issues so the maintainers can address the root cause.

There is not a command to explicitly restart `gopls`, but you do have options (ordered from most to least preferred):
* execute `GoBuildTags` with any argument (e.g. `:GoBuildTags ''` to reset build tags or with a comma separated list of the build tags you want to use) to cause `gopls` to be reconfigured. I suspect this may be enough to fix the issues you're seeing.
* execute `GoUpdateBinaries gopls` to reinstall `gopls`; that will cause `gopls` to be restarted by vim-go.
* execute `call go#lsp#Restart()`.
* execute `call go#lsp#Exit()` this isn't much better than just killing `gopls`.

Honestly, those last two functions may change in the future and aren't currently intended for users to call explicitly.

**Comment by mnarrell** [comment]
Thanks Billie, you’re doing great work.

**Comment by beastoin** [comment]
Thanks @bhcleek , just using map to call `call go#lsp#Exit()` manually when needed

**Comment by wangtiga** [comment]
```shell
" vim-go: no identifier found
" vim-go: no object found for ident AddAllMemberId: no object found

:GoBuildTags ''`
```


This resolved my problem. Thank you so much.

**Comment by jinleileiking** [comment]
This should be in `:help vim-go`
