### ISSUE TITLE
GoReferrers not work with scope and error message appears at bottom

### ISSUE THREAD

**Issue by hehailong5** [fatih/vim-go#2565]
What did you do? (required: The issue will be closed when not provided)
1) :GoGuruScope  /root/hhl/git/msb-apigateway-go/apiroute/src/apiroute/...
2) :GoReferrers for an identifier

What did you expect to happen?
list all the referrers for this identifier within specified scope

What happened instead?
1) only list referrers within current package
2) error appears at bottom:
vim-go: /root/hhl/git/msb-apigateway-go/apiroute/src/apiroute/cache/re...e: -1 at function 374[13]..377[26]..111_referencesHandler, line 12

Configuration (MUST fill this out):
vim-go version:
tried both v1.21 and master

vimrc you used to reproduce (use a minimal vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
root@nfvo1-E9000:~# cat .vimrc.go
set runtimepath^="/root/.vim_go_runtime"

source /root/.vim_go_runtime/vimrc/basic.vim
source /root/.vim_go_runtime/vimrc/filetypes.vim
source /root/.vim_go_runtime/vimrc/plugins.vim
source /root/.vim_go_runtime/vimrc/extended.vim

try
source /root/.vim_go_runtime/custom_config.vim
catch
endtry

Vim version (first three lines from :version):
8.1.2151

Go version (go version):
go1.12.10

Go environment
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/hhl/go:/root/hhl/git/msb-apigateway-go/apiroute:/root/hhl/git/msb-sdclient-go/sdclient"
GOPROXY=""
GORACE=""
GOROOT="/root/.gvm/gos/go1.12.10"
GOTMPDIR=""
GOTOOLDIR="/root/.gvm/gos/go1.12.10/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build551488242=/tmp/go-build -gno-record-gcc-switches"

**Comment by bhcleek** [comment]
`:GoGuruScope` isn't relevant for `:GoGuruScope` on master, and you shouldn't be getting the same error for 1.21 and for master, because they use completely different code paths for `:GoReferrers`. Can you confirm that you're only seeing that error for master and not for 1.21?

Generally, `:GoReferrers` works well on master: I'm using it daily. I'll need a clear replication path (files, etc.) that demonstrate the problem to really get to the bottom of this.

**Comment by hehailong5** [comment]
I just replaced the vim-go in bundle with the vim-go-master.zip, and :GoReferrers only works for current package and the error would only appear in the first attempt. 
b.t.w, how to check the vim-go version exactly, I was looking in the CHANGELOG.md for it.

**Comment by bhcleek** [comment]
Does vim-go-master.zip mean that you just downloaded vim-go from GitHub using 
![image](https://user-images.githubusercontent.com/1958864/68446529-d09c2080-0191-11ea-89c7-36471b970c34.png) ? If so, then the version you're using is latest master (assuming that you didn't navigate to a different commit).

> only works for the current package and the error would only appear on the first attempt

This doesn't tell me how to duplicate your problem. Think of it from my perspective: I run `:GoReferrers` regularly without a problem. Since it's not working for you something there is likely something about your environment or the files you're using that may be relevant. How can I duplicate your problem?

**Comment by bhcleek** [comment]
I've been able to confirm that gopls is only returning references in the current package. I'll see if I can find a bug report about that for gopls.

**Comment by bhcleek** [comment]
https://github.com/golang/go/issues/32869 for the single package references issue. I'll likely add an option to allow users to choose whether to use guru or gopls for `:GoReferrers`.

**Comment by hehailong5** [comment]
Hi,
Yes, I was fetching the latest master with the way as you described above.
So how to verify if I was using gopls for :GoReferrers and how to switch to guru?

**Comment by bhcleek** [comment]
master does not allow you to switch between guru and gopls for `:GoReferrers`. It only supports gopls right now, but I'm working on a PR to allow you to choose so to use guru instead. As it stands at the moment, you would need to install a version of vim-go prior to https://github.com/fatih/vim-go/commit/94a266b8e60692ba760efe982a5ecb8f2d841704 to use guru.

However, I've found a way to duplicate the error you're seeing and hope to have a fix soon.

**Comment by bhcleek** [comment]
@haya14busa can you confirm whether #2566 resolves the two problems you've encountered?
