### ISSUE TITLE
Error message when opening a go file directly from the command line

### ISSUE THREAD

**Issue by urandom** [fatih/vim-go#2600]
### What did you do? (required: The issue will be **closed** when not provided)

`$ nvim some_file.go`

### What did you expect to happen?

I expected the file to be opened without a problem

### What happened instead?

```
Error detected while processing /home/urandom/.config/nvim/plugged/vim-go/ftplugin/go.vim:                                                                                                                   
line   28:
E117: Unknown function: go#config#CodeCompletionEnabled
E15: Invalid expression: go#config#CodeCompletionEnabled()

```

### Configuration (**MUST** fill this out):
```
set ignorecase
set nomodeline
set smartcase
set ruler
set showcmd
set cursorline
set number
set showbreak=↳
set hidden
set undofile
set shiftwidth=4
set tabstop=4
set clipboard=unnamed
set shortmess+=c
set updatetime=300
set signcolumn=yes
set expandtab
set wildmode=longest:full
set pumblend=20

set go-=T,e,r,L,m
set go+=c
set completeopt=longest,noinsert,menuone,noselect
set suffixes=.bak,~,.swp,.o,.info,.aux,.log,.dvi,.bbl,.blg,.brf,.cb,.ind,.idx,.ilg,.inx,.out,.toc
set wildignore+=*.o,*.obj,*.jpg,*.gif,*.png,*.jar,*.zip,*.jpeg,*.tif*,*.exe,*.jpe,*.pdf,*.doc,*.mo,*.svg,*.cache,*.mp4,*.class,*.a
set termguicolors
set inccommand=nosplit
set mouse=a
set guifont=Fira\ Code:h12

scriptencoding utf-8
syn on

call plug#begin('~/.config/nvim/plugged')

try
    " languages
	Plug 'fatih/vim-go'

    " completion
    Plug 'autozimu/LanguageClient-neovim', {
    \ 'branch': 'next',
    \ 'do': 'bash install.sh',
    \ }
    Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
    Plug 'ncm2/float-preview.nvim'

    " misc
	Plug 'dense-analysis/ale'
    Plug 'simnalamburt/vim-mundo'
	Plug 'tpope/vim-fugitive'
	Plug 'itchyny/lightline.vim'

    " files
    Plug 'liuchengxu/vim-clap'
    Plug 'scrooloose/nerdtree', { 'on': ['NERDTreeToggle', 'NERDTreeFind'] }
    Plug 'Xuyuanp/nerdtree-git-plugin', { 'on': ['NERDTreeToggle', 'NERDTreeFind'] }
catch
endt

call plug#end()
let g:go_fmt_command = "goimports"
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_structs = 1
let g:go_term_enabled = 1
let g:go_addtags_transform = "camelcase"
let g:go_def_mode = 'gopls' 
let g:go_code_completion_enabled = 0
let g:go_auto_sameids = 1
let g:go_gocode_autobuild = 1
let g:go_gocode_unimported_packages = 1
```

#### vim-go version:
vim-go: 1.21

#### Vim version (first three lines from `:version`):
NVIM v0.4.3

#### Go version (`go version`):
go version go1.13.4 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/urandom/.cache/go-build"
GOENV="/home/urandom/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/urandom/.go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/tmp/gio/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build370147346=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

**Comment by bhcleek** [comment]
This looks like a polyglot issue, but according to the config you posted, you don't have polyglot installed. Can you confirm that you are not using polyglot? (ref: https://github.com/fatih/vim-go/issues/2272#issuecomment-489481142).

FWIW, take a look at `/home/urandom/.config/nvim/plugged/vim-go/autoload/go/config.vim`, and I think you'll see that `go#config#CompletionEnabled` is there. If it is, then the issue is something about your configuration and not a result of a bug in vim-go.

**Comment by urandom** [comment]
I'm not using polyglot. I am aware of the linked issue, but it doesn't appear to apply to my setup. I'm not sure how this is not a bug in vim-go, even if it was my configuration. Yes, I'm setting `go_code_completion_enabled`, because I was hoping it would alleviate the problem. It turns out it does nothing to prevent it, though in any case, it shouldn't be needed even if it did.

**Comment by bhcleek** [comment]
The reason I don't think it's a bug in vim-go is because the function _is_ defined in v1.21: https://github.com/fatih/vim-go/blob/v1.21/autoload/go/config.vim#L478-L480.

By "your config," I don't mean your vimrc necessarily. It could be an older version of vim-go installed some place. You can see where functions are defined from by running `:verbose function`, and you can zero in on a single function by appending the function name.  With that knowledge, we can run `verbose function go#config#AutodetectGopath` to see where the `go#config#AutodetectGopath` function is set from. Since it should be in the same file as `go#config#CompletionEnabled` and predates `go#config#CompletionEnabled` by a long time, we can use that to figure out where vim-go's config functions are being loaded from. It _should_ be `/home/urandom/.config/nvim/plugged/vim-go/autoload/go/config.vim` on your system.

**Comment by urandom** [comment]
Actually, `verbose function go#config#CodeCompletionEnabled`                                                                                                                                                  

returns `E123: Undefined function: go#config#CodeCompletionEnabled`              

It's like the autoload files are never sourced

**Comment by bhcleek** [comment]
Given the error you're experiencing with vim-go, that's exactly the output I'd expect from `verbose function go#config#CodeCompletionEnable`. 

Please run `verbose function go#config#AutodetectGopath` instead.

**Comment by urandom** [comment]
I have up and copied the configuration from another computer. Since that fixed it, its clear that the problem was a local configuration, though I cannot say what for sure.
