### ISSUE TITLE
GoRename does nothing

### ISSUE THREAD

**Issue by ViRu-ThE-ViRuS** [fatih/vim-go#2617]
### What did you do? (required: The issue will be **closed** when not provided)
:GoRename

`:GoRename` on a variable name, prompted for new name, enter... no result, no error, no message, no log

### What did you expect to happen?
Renaming the variable to the new provided name

### What happened instead?
Nothing, no error, no crash, no log

### Configuration (**MUST** fill this out):
GOPATH, GOROOT, go_bin_path properly set
GoDoc works, GoDef works, GoRefs works
gorename from shell works

pwd: /Users/viraat-chandra/Workspace/work/go_space/src/Gunther

#### vim-go version:
v1.21

####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
<details><summary>vimrc</summary><br><pre>
call plug#begin('~/.config/nvim/plugged')
Plug 'deoplete-plugins/deoplete-go', {'for': 'go', 'do': 'make'}
Plug 'fatih/vim-go', {'for': 'go', 'do': ':GoUpdateBinaries'}
call plug#end()

set encoding=utf-8
set history=100
set autoread
set hidden

let g:syntastic_go_checkers=['gofmt']
let g:go_highlight_extra_types=1
let g:go_highlight_fields=1
let g:go_highlight_functions=1
let g:go_highlight_function_calls=1
let g:go_highlight_methods=1
let g:go_highlight_operators=1
let g:go_highlight_structs=1
let g:go_highlight_types=1

let g:deoplete#sources#go#gocode_binary=$GOBIN.'/gocode'
let g:deoplete#sources#go#source_importer=1
let g:deoplete#sources#go#pointer=1

let g:go_fmt_command='goimports'
let g:go_addtags_transform='snakecase'
let g:go_list_type='quickfix'

autocmd FileType go nmap <leader>d :GoDef<CR>
autocmd FileType go nmap <leader>n :GoRef<CR>
autocmd FileType go let $GOPATH=$GOPATH.":/Users/viraat-chandra/Workspace/work/go_space/"
</pre></details>

#### Vim version (first three lines from `:version`):

NVim 0.4.3

#### Go version (`go version`):

1.13.5

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN="/Users/viraat-chandra/.dev/go/bin"
GOCACHE="/Users/viraat-chandra/Library/Caches/go-build"
GOENV="/Users/viraat-chandra/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/viraat-chandra/.dev/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/s0/chvs8h1s42j7lxrgb4_wtqgw0000gn/T/go-build215807119=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

**Comment by bhcleek** [comment]
Your working directory is `/Users/viraat-chandra/Workspace/work/go_space/src/Gunther`, your GOPATH is `/Users/viraat-chandra/.dev/go`, and you're using vim-go 1.21.

Since the code you're editing is not in GOPATH, you'll be in module aware mode (do you have an ambient `go.mod` file?), but vim-go 1.21 still uses `gorename` for `:GoRename`. `gorename` does not support Go modules.

You have two options: put your source code in GOPATH or update vim-go to a version that can use `gopls rename` for renaming. Current master has supported `gopls rename` for `:GoRename` for a while now. If you choose the latter, then only the files in the package where you're running `:GoRename` will be renamed due to a current limitation with `gopls rename`. If you choose the former, then probably want to to also set `g:go_rename_command='gorename'` so that `gorename` will be used.

**Comment by ViRu-ThE-ViRuS** [comment]
okay, that makes sense... closing here
