### ISSUE TITLE
Double slashes in a string break indentation.

### ISSUE THREAD

**Issue by brightpuddle** [fatih/vim-go#2625]
### What did you do?
Create an indent line with a string containing double forward slashes: `"//"`, e.g.
```go
package main

func main() {
	if "//" == "//" {
	println("!!!")
}
}
```

### What did you expect to happen?
Correct indentation.

### What happened instead?
`"//"` causes opening bracket indentation to be ignored.

#### vim-go version:
1.21 + latest patches.

####  `vimrc` you used to reproduce:
```
call plug#begin('~/.vim/plugged')
Plug 'fatih/vim-go', {'for': 'go'}
call plug#end()
```

#### Vim version:
`NVIM v0.4.3`

#### Go version:
`go1.13.4 darwin/amd64`

**Comment by bhcleek** [comment]
Thank you for the report. Given that formatting works correctly (e.g. `:GoFmt` or writing the file with `g:go_fmt_autosave=1`, the default, set), am I correct to assume that your concern is the auto indent behavior in insert mode?

**Comment by brightpuddle** [comment]
Yes, that's correct. The file doesn't indent correctly in insert mode, but saving it indents properly. It only happens when the `//` is on the same line as the opening bracket.

**Comment by bhcleek** [comment]
Because this is a very rare edge case, solves itself when saving or running `:GoFmt`, and adjusting the `comments` option (see `:help 'comments'`) at https://github.com/fatih/vim-go/blob/master/ftplugin/go.vim#L21 would likely be error prone and end up with still some edge cases, I'm inclined to close this without attempting a fix.
