### ISSUE TITLE
Fails under Mingw on windows 10

### ISSUE THREAD

**Issue by gshields** [fatih/vim-go#2682]
Installed using:
git clone https://github.com/fatih/vim-go.git \
      ~/.vim/pack/plugins/start/vim-go

These work:
GoUpdateBinaries, GoInstallBinaries, GoInstall

GoDoc, GoRun, GoDebugStart, GoBuild 
All report E492: Not an editor command: xxx where xxx was the above command
The go and dlv work from the same bash shell

Window 10 with Mingw bash and Go 1.13.7 vim  8.1.2292

**Comment by bhcleek** [comment]
There's not enough information here for me to diagnose well.

Here's what we know:
1. `:GoUpdateBinaries` and `:GoInstallBinaries` are available always, because they come from the plugin portion of vim-go.
1. The fact that `:GoInstall` is available indicates that you probably have filetype detection turned on, but the absence of `:GoDoc`, `:GoRun`, abnd `:GoDebugStart` indicate that perhaps you do not.

What does the output of `:messages` after opening a go file show?

Do you have a minimal vimrc and any of the other information that the issue template asked for?

**Comment by gshields** [comment]
.vimrc was missing so I added this
...................
set ruler
filetype indent on
...................

Now Godoc and GoRun work!   Thanks!

But GoBuild still does not from within vim, however it does at the command
line.
Running the GoBuild command show a message of "dispatched" and then the
message of "success"
I exited vim and looked to see the exe and it did not create the exe.
if I then run go build at the bash prompt it builds the exe.
I uninstall Mingw and just have
git version 2.25.0.windows.1
go version go1.13.7 windows/amd64
window 10 v 1909

**Comment by bhcleek** [comment]
`:GoBuild` does not produce a file, but you can use `:make` to produce one.

ref: https://github.com/fatih/vim-go/blob/master/doc/vim-go.txt#L349-L352.

You'll want to use `filetype plugin indent on` to make sure that everything is loaded correctly: https://github.com/fatih/vim-go/blob/master/doc/vim-go.txt#L2374-L2380.

The vim-go help is relatively extensive.

**Comment by bhcleek** [comment]
@gshields since the filetype commands are working as expected, I think we can close this. Do you disagree?

**Comment by gshields** [comment]
Yes thanks for your help
