### ISSUE TITLE
multiple 'analysis skipped' errors

### ISSUE THREAD

**Issue by Integralist** [fatih/vim-go#2722]
### What did you do? (required: The issue will be **closed** when not provided)

Opened a `.go` file, made some code changes and then `:w` to write the buffer back to the file. 

### What did you expect to happen?

Because the changes I had made would have caused the `go build` command to fail (e.g. invalid code syntax), I expected the location list to open with a list of errors for that file I was editing.

### What happened instead?

The location window opened but there were two lines of errors not related to the code file, but errors with running the static analysis tools used by vim-go...

```
perimeter/internal/pkg/proxy/base.go|760 col 7 warning| [runner] Can't run linter goanalysis_metalinter: asmdecl: analysis skipped: errors in package
perimeter/internal/pkg/proxy/base.go|760 col 7 error| Running error: asmdecl: analysis skipped: errors in package
```

### Configuration (**MUST** fill this out):

```viml
Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }

...

let g:go_fmt_command = 'goimports'
let g:go_metalinter_autosave = 1
let g:go_metalinter_deadline = '20s'

autocmd FileType go imap /. <C-x><C-o>
```

#### vim-go version:

v1.22

####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
<details><summary>vimrc</summary><br><pre>
set nocompatible
set nobackup
set nowritebackup
set noswapfile

call plug#begin('~/.vim/plugged')

Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }

call plug#end()

let g:go_fmt_command = 'goimports'
let g:go_metalinter_autosave = 1
let g:go_metalinter_deadline = '20s'

autocmd FileType go imap /. <C-x><C-o>
</pre></details>

#### Vim version (first three lines from `:version`):

```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Aug 12 2019 11:40:34)
macOS version
Included patches: 1-1839
```

#### Go version (`go version`):

```
go version go1.13 darwin/amd64
```

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/markmcdonnell/Library/Caches/go-build"
GOENV="/Users/markmcdonnell/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/markmcdonnell/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.13/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.13/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/zk/_jgd9h392p55w9fd4lzt5dpw0000gp/T/go-build183558573=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.3.1
    golang.org/x/tools/gopls@v0.3.1 h1:yNTWrf4gc4Or0UecjOas5pzOa3BL0WDDyKDV4Wz5VaM=
</pre></details>

**Comment by Integralist** [comment]
Worth noting that `golint` appears to work though...

```
1 internal/pkg/proxy/base.go|157 col 9| if block ends with a return statement, so drop this else and outdent its block (move short variable declaration to its own line if necessary) (golint)
```

**Comment by bhcleek** [comment]
This is happening because you're using `g:go_metalinter_autosave_enabled=1` and `g:go_metalinter_command='golangci-lint'` and that's picking up errors that were previously hidden but were necessarily exposed in #2706. I suspect that either disabling metalinting on save or else using `gopls` as the metalinter will solve this for you.

Long term, I can look at a better way to handle the situation where formatting (which necessarily happens before the buffer is saved) and metalinting on save won't hide the errors returned from formatting. Unfortunately, there's not much that I can do about the golangci-lint errors; it just doesn't return anything super helpful in this case.

I've seen lots of problems like this related to golangci-lint; I'm considering changing the default value for `g:go_metalinter_command` to `gopls`. I'm curious about your thoughts to that, because you've reported  several problems recently. 🤔

**Comment by Integralist** [comment]
I'd be in favour of this as it seems like a reasonable default. Especially considering the number of issues reported recently and the fact that golangci-lint isn't able to return anything useful. 👍

So you're suggesting changing command to gopls and also disabling autosave feature...  `g:go_metalinter_autosave_enabled=0`

**Comment by bhcleek** [comment]
Thanks for the feedback!

> So you're suggesting changing command to gopls and also disabling autosave feature... g:go_metalinter_autosave_enabled=0

I don't think you need to do both; one or the other will likely be sufficient. Disabling `g:go_metalinter_autosave_enabled` when using golangci-lint as the metalinter would be useful, because that golangci-lint isn't reporting anything useful when there's a fundamental compilation error.

On the other hand, if you want to metalint on save, then using `gopls` will be useful, because I'd expect it to also tell you about the compilation errors, so even though it would overwrite the error from formatting, the error from formatting will likely be included in the gopls output, too. If you do use `let g:go_metalinter_command='gopls'`, you'll probably also want to `let g:go_gopls_staticcheck = 1`.

**Comment by Integralist** [comment]
Awesome, thanks! I'll try this out this morning and report back 👍

**Comment by Integralist** [comment]
So I opted for using...

```viml
let g:go_fmt_command = 'goimports'
let g:go_metalinter_command='gopls'
let g:go_gopls_staticcheck = 1
let g:go_metalinter_autosave = 1
let g:go_metalinter_deadline = '20s'
```

Which works ...almost? 

Pros...

- I get error messages show in the location list 🎉 

Cons...

- after a `:w` it takes 10 seconds for me to be able to interact with the buffer (e.g. move my cursor) which is massively slowing me down.
- after fixing an issue I'll execute `:w` of couse to save the changes, but I discover the last issue I just fixed will still show in the location list and so I have to do one extra `:w` to get the list to finally clear and show a PASS message!


The one thing I would say is that it's _very_ slow when I do `:w`. What I mean by that is when I write the buffer it takes (almost consistently) 10 seconds before I can interact with the buffer (e.g. move the cursor around)?

**Comment by Integralist** [comment]
Additionally some errors, such as...

```
missing ',' before newline in composite literal
```

...are caught asynchronously when using [ALE](https://github.com/dense-analysis/ale). So I wonder if there's configuration within the ALE plugin that can ease the problems I'm having with the 10s feedback loop delay 

e.g. [there looks to be a gopls file as part of ALE's go support](https://github.com/dense-analysis/ale/tree/master/ale_linters/go).

**Comment by bhcleek** [comment]
yeah, ALE can use gopls now, too. The Go tools team is working on adding multiple client support to gopls, too.

The ten second delay you're seeing is because after a write, vim-go only waits for a maximum of ten seconds before displaying any diagnostics about the current file when `g:go_metalinter_autosave` is set. I can probably improve that situation pretty easily; I'll see what I can do.

**Comment by bhcleek** [comment]
@Integralist can you give #2733 a try with golangci-lint set as your metalinter and `g:go_metalinter_autosave` enabled?

**Comment by bhcleek** [comment]
@Integralist that PR isn't ready yet; I'm writing some tests that show that it's not working as expected quite yet. I'll let you know when it's ready.

**Comment by bhcleek** [comment]
@Integralist #2733 is ready if you want to give it a try before I merge it.

**Comment by Integralist** [comment]
Apologies. I've been so snowed under at work I've not had a chance to look at this.
