### ISSUE TITLE
[Feature request] Support gopls daemon mode

### ISSUE THREAD

**Issue by luisdavim** [fatih/vim-go#2760]
It would be a nice performance improvement if vim-go could support talking to a daemon gopls or maybe even managing the daemon instance so other plugins like coc.vim or YouCompleteMe can use it.

Some relevant links

- https://github.com/golang/tools/blob/master/gopls/doc/daemon.md
- https://github.com/golang/go/issues/34111
- https://github.com/fatih/vim-go/issues/2421

**Comment by luisdavim** [comment]
Looks like all we have to do is to add `-remote=auto` to the `gopls` args, maybe all we need is to document this, here's an example with `coc.nvim`

`vim-go` relevant config:
```
  let g:go_gopls_enabled = 1
  let g:go_gopls_options = ['-remote=auto']
  let g:go_def_mode='gopls'
  let g:go_info_mode='gopls'
  let g:go_referrers_mode = 'gopls'
```

and got `coc.nvim`:
```
  "languageserver": {
    "golang": {
      "command": "gopls",
      "args": ["-remote=auto"],
      "rootPatterns": ["go.mod", ".vim/", ".git/", ".hg/"],
      "filetypes": ["go"]
    }
  }
```

**Comment by bhcleek** [comment]
Thank you for the suggestion. 

Yes, this is already suported by using `g:go_gopls_options`; `-remote=auto` was one of the motivations for adding `g:go_gopls_options`. I don't intend to document it explicitly, because I intend to make the default for `g:go_gopls_options` be `-remote=auto` by the next release. I've been running my machine like since gopls v0.3.3 came out.

**Comment by ygworldr** [comment]
@luisdavim Something I am doing is not working [so I opened this issue](https://github.com/josa42/coc-go/issues/76).

**Comment by ericwq** [comment]
see [this](https://github.com/ericwq/golangIDE/blob/master/shared-gopls-daemon.md) for the reason.
