### ISSUE TITLE
parseLocalPackage error: no more package files found^@godef: no declaration found for bigquery.BigqueryScope

### ISSUE THREAD

**Issue by oryband** [fatih/vim-go#277]
```go
package main

import (
    "fmt"
    "google.golang.org/api/bigquery/v2"
)

func main() {
    fmt.Println(bigquery.BigueryScope)  // try `go-def`-ing bigquery.BigqueryScope
}
```
This will echo the following message in vim:
```vim
parseLocalPackage error: no more package files found^@godef: no declaration found for bigquery.BigqueryScope
```

This is just an example, all `go-def`s don't work with Google's BigQuery Go library. Maybe because of the way code is stored in the above github repo, I don't know. This prevents me from go-to-source when working with Google libraries :\

Same happens if I try to `import "code.google.com/p/google-api-go-client/bigquery/v2"` instead of `google.golang.org/...`.

Any idea why?

**Comment by oryband** [comment]
@fatih this indeed works, thanks! But why aliasing `bigquery` necessary for `go-def` to work?

**Comment by fatih** [comment]
@oryband it seems yes. Let me ping @rogpeppe as he is the original author of the `godef` binary, he can give more insight :)

**Comment by oryband** [comment]
@fatih so don't close this yet! I want to know why, perhaps there's a problem which required more work.

**Comment by fatih** [comment]
Alright let this keep open until rog replies. Maybe there is something I need to modify in our wrapper around `godef`.

**Comment by oryband** [comment]
:+1:

**Comment by rogpeppe** [comment]
I'm sorry about this - it's an early (and intentional though misguided) decision made when implementing godef. Currently godef, when there's no identifier explicitly in the import line, assumes that it can determine the identifier from the import path. This is why fatih's suggestion above works.

The reason for this is that it means that we know exactly when we need to open an external file to find out where a symbol is defined, so finding symbols can be very fast.

Unfortunately it doesn't work, for the reasons we see above, and I should really spend some time fixing this issue!

"." imports don't work either FWIW.

As a quick fix, there is already a special case for packages that end with a .vN (version) suffix; we could perhaps make another special case for the /vN suffix, although that has more potential to go wrong (next time someone imports a V8 javascript interpreter...)

**Comment by fatih** [comment]
Thanks for the insight @rogpeppe. I don't keep issues open when I can't do nothing on my side, so for this I'll close until Rog has a fix for it, as there is not much for me to do. At least we know now why it doesn't work or under which circumstances it'll work.

**Comment by oryband** [comment]
@rogpeppe thx for the answer. Can you please report this issue upstream to godef repo, and ref this issue, so we can follow this issue there?
@fatih thx for the tech support :)

**Comment by oryband** [comment]
@fatih @rogpeppe i couldn't find a `go-def` active repo anywhere. Can you spare a link plz?

**Comment by rogpeppe** [comment]
It's still stored in https://code.google.com/p/rog-go/ which is somewhat outdated.
I will move it to github soon.

**Comment by oryband** [comment]
@rogpeppe any news?

**Comment by rogpeppe** [comment]
I'm afraid I haven't yet managed to fix the issue, but the repo is on github, at least: https://github.com/rogpeppe/godef

**Comment by oryband** [comment]
@rogpeppe care to create a new issue and reference this one please?

**Comment by rkulla** [comment]
What ever happened with this? I still have to use the alias trick for the latest vim-go to godef properly

**Comment by oryband** [comment]
abandoned, i guess

**Comment by heipacker** [comment]
the godef repo no man maintain?

**Comment by rogpeppe** [comment]
The godef repo is maintained but I don't have enough spare time to fix substantial issues with it currently,  I'm afraid. PRs gratefully received, but given that the guru tool now supports "show location of definition", in a more comprehensive (though probably slower) way,  it may be best just to move to using that.

**Comment by fatih** [comment]
Thanks @rogpeppe for all the hard work. @heipacker we switched to `guru definition` in the new version. It's slower than @rogpeppe's godef, but it handles cases like this better.
