### ISSUE TITLE
Suggestion: Go Format on Window Close

### ISSUE THREAD

**Issue by eL0ck** [fatih/vim-go#2771]
I find that doing a formatting on every save with `let g:go_fmt_autosave = 1` is a little much for me.   I'm happy enough if a format is done when i'm done with the file.

Suggest a parameter such as `let g:go_fmt_autoclose = 1` that defaults to `0` (off).

PR to follow

**Comment by bhcleek** [comment]
If that's your desire, then I'd suggest turning off the fmt in save and write a simple autocmd to call `:GoFmt` on `BufWinLeave` .

I'm unlikely to merge a PR that does what you describe, because the feature isn't generally needed, and adding an autocmd to your vimrc is a simple fix for your preferred workflow.

**Comment by eL0ck** [comment]
Good point.  Got a bit trigger happy there.

**Comment by bhcleek** [comment]
No worries. Your willingness to contribute is much appreciated! Please don't let this discourage you from making future contributions.
