### ISSUE TITLE
gopls 0.4.0 and goreturns, when to upgrade gopls ?

### ISSUE THREAD

**Issue by flibustenet** [fatih/vim-go#2819]
Hi,

The v0.4.0 of gopls seems to add goreturns feature, i would like to test it, but i don't know how to add the vscode example configuration :

```
"gopls": {
	"analyses": {
		"fillreturns": true,
                "undeclaredname": true,
                "unusedparams": true,
                "nonewvars": true,
	}
}
```

But more generally I wonder when I can upgrade gopls. Should I wait that vim-go include the last features of gopls or is it safe to upgrade gopls when it's released ?

Thanks

**Comment by bhcleek** [comment]
It's generally safe to update gopls without waiting for vim-go to officially support it, because gopls relies on a protocol that the Go tools team is trying hard to support reliably and they're also putting a lot of care into backward compatibility.

The new analyses aren't supported yet. I'll put up a PR soon to refactor a few things to make it easier to adapt when gopls adds new configs so that a PR won't be required after future gopls releases that add new workspace level configs.

**Comment by flibustenet** [comment]
Thanks but sorry could you give an example how to set an option like fillreturns ?

**Comment by bhcleek** [comment]
`let g:go_gopls_config={'fillreturns': v:true}`

**Comment by flibustenet** [comment]
I will look that, thanks
