### ISSUE TITLE
vim-go stopped working, asking for golist.go:144

### ISSUE THREAD

**Issue by peterfeifanchen** [fatih/vim-go#2827]
I have vim-go installed in path ~/.vim/pack/plugins/start and I checked out v1.22. When I go :GoInstallBinaries, it tells me everything has been installed. Everything was working from last week but today, when I try gd or any vim-go commands I get

`vim-go:         third_party/golang/go_tools/go/packages/golist.go:144 +0x208`

### What happened instead?
I expected vim to jump to the declaration of the code for gd. Also when I save, I expected it to flag extraneous or missing packages. That both no longer happens, to be replaced by the above on my vim screen at the bottom. 

#### vim-go version:
v1.22

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary><br><pre>
set nocompatible
set number
filetype plugin indent on
syntax on
set shiftwidth=4
set tabstop=4
set hlsearch
colo delek

</pre></details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.1 (2018 May 18, compiled Nov 19 2019 14:03:20)
Included patches: 1-2269
Modified by team+vim@tracker.debian.org

#### Go version (`go version`):

go version go1.14 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/usr/local/google/home/chenfeif/.cache/go-build"
GOENV="/usr/local/google/home/chenfeif/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/usr/local/google/home/chenfeif/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/google-golang"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/google-golang/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build545573298=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

#### gopls version
<details><summary><code>gopls version</code> </summary><br><pre>

golang.org/x/tools/gopls 0.2.2
golang.org/x/tools/gopls@v0.2.2 h1:ujGisyytgY1VGcmd66wIJ9+wVAfmodXj6daHM43HRXk=
</pre></details>

**Comment by bhcleek** [comment]
`:GoInstallBinaries` does not update anything; it [only installs missing binaries](https://github.com/fatih/vim-go/blob/master/doc/vim-go.txt#L501-L507) (see [`:help :GoInstallBinaries`](https://github.com/fatih/vim-go/blob/master/doc/vim-go.txt#L501-L507)). I suspect you want `:GoUpdateBinaries` (see [`:help :GoUpdateBinaries`](https://github.com/fatih/vim-go/blob/master/doc/vim-go.txt#L511-L519))

However, that error is odd; it doesn't come directly from vim-go, and based on what you've reported for your .vimrc, you should be [using `gopls` for `g:go_def_mode`](https://github.com/fatih/vim-go/blob/v1.22/autoload/go/config.vim#L205-L207), and there is no `third_party` directory anywhere in [`golang.org/x/tools` repository at gopls/v0.2.2 tag](https://github.com/golang/tools/tree/gopls/v0.2.2).

Vim-go does not magically update binaries on your machine, nor does it update itself automagically. If this was working on your system last week, what's changed since then?

**Comment by peterfeifanchen** [comment]
I am not sure what can have changed...I've commented out the standard vimrc that I source for the company I work for. So that just leaves the vimrc I have above and it still doesn't work. I tried GoUpdateBinaries and I tried to install it using vundle too. It displays the same error.  It is working for a coworker still though...it is very strange.

**Comment by peterfeifanchen** [comment]
Hmm ok, things started working again after I restarted my computer. Is there some state that vim-go depends on somewhere outside of .vimrc or something that gets reset by a restart?

**Comment by bhcleek** [comment]
vim-go itself does not keep any state
