### ISSUE TITLE
"botright" for quickfix window?

### ISSUE THREAD

**Issue by pachanga** [fatih/vim-go#2946]
Hi! What do you think of using "botright copen" in go#list#Window instead of just "copen"? Or at least make it configurable? "botright" really makes quickfix window more convenient to use when working with several vertical splits.

**Comment by bhcleek** [comment]
The quickfix list is opened to a specific height by using `:execute`. `:botright` doesn't work with `:execute`.

**Comment by pachanga** [comment]
I patched it this way and it works in Neovim: https://github.com/pachanga/vim-go/commit/7210598114b82dab77bc4af4baee0cc79e828ce9

**Comment by bhcleek** [comment]
I misunderstood the `:help botright` language on this. What you've proposed will work in Vim, too, but I'd rather not complicate vim-go with an option when you can control it yourself easily by using some autocmds in your vimrc, especially because if this is the kind of behavior you generally want, then adding an option for this to vim-go wouldn't apply more widely.

Alternatively, you can control this with your vimrc by adding `autocmd FileType qf wincmd L` as documented by https://stackoverflow.com/a/6728687/283776 and is also discussed in https://github.com/fatih/vim-go/issues/1757.

**Comment by pachanga** [comment]
Thanks!
