### ISSUE TITLE
Run project not in main package

### ISSUE THREAD

**Issue by bkielbasa** [fatih/vim-go#3025]
## The problem
When I'm working on a project, very often I edit files in sub-packages. When I want to run the project I have to jump to the main package and call `:GoRun` there. That can be frustrating at some point.

## The proposal
vim-go could try to detect the main package in the project tree up to the workspace root.

```
/.
. main.go
|-subpkg
  |- file.go <- I'm editing this file right now (current-buffer)
  |- file2.go
```

During editing `file.go` or `file2.go` I'd like to be able to run the project anyway. vim-go could go to the package's parent and check if it's the main package and if yes - run `:GoRun` there.

That would be very handy :)

**Comment by bhcleek** [comment]
This isn't really possible to do in a way that's always going to be correct, because vim-go is not a Go parser. There are a number of situations where the suggested feature would run into irreconcilable difficulties:
1. some `main` package in a parent directory is fully guarded by build tags; how should those build constraints be evaluated for whether or not `:GoRun` should treat the package as the package to run.
2. how to deal with `GO111MODULE` values in different scenarios
3. running `go list` on each directory above the current buffer would be cost prohibitive and would likely result in user complaints
4. What should the working directory be set to in your scenario? The current implementation of `:GoRun` is very clear on what the working directory is.

If you know the package that you want to run, you can provide the import path to `:GoRun` (e.g.: `:GoRun ..`) instead of editing one of the files in the package and then executing `:GoRun`.

**Comment by bkielbasa** [comment]
thanks for the feedback. Is there a way putting to `:GoRun` the workspace root to evaluate it to `:GoRun /path/to/my/project`

**Comment by bhcleek** [comment]
`:GoRun` sets the working directory to the directory that contains the active buffer.
