### ISSUE TITLE
Syntax: Ignore spelling for go imports

### ISSUE THREAD

**Issue by palsivertsen** [fatih/vim-go#3063]
### What did you do? (required: The issue will be **closed** when not provided)
Opened a go file with some imports and enabled spell checking.

![Peek 2020-10-21 10-48](https://user-images.githubusercontent.com/11890143/96696811-7d63b380-138b-11eb-9014-0f118c979671.gif)

### What did you expect to happen?
Imports should not be spellchecked.

### What happened instead?
Import string was spellchecked (see .gif above).

####  `vimrc` you used to reproduce:

(Not the one used to record the gif, but same results)
<details><summary>vimrc</summary><br><pre>
call plug#begin()
Plug 'fatih/vim-go', { 'do': ':GoInstallBinaries' }
call plug#end()

autocmd Filetype go set spell
</pre></details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Sep 17 2020 21:54:53)
Included patches: 1-1704
Compiled by Arch Linux

#### Go version (`go version`):

go version go1.15.3 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/pal/.cache/go-build"
GOENV="/home/pal/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/pal/projects/go/pkg/mod"
GONOPROXY="REDACTED"
GONOSUMDB="REDACTED"
GOOS="linux"
GOPATH="/home/pal/projects/go"
GOPRIVATE="REDACTED"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="REDACTED"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build902176203=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls 0.4.4
    golang.org/x/tools/gopls@v0.4.4 h1:8djGYsaZ0ByP0vaXg4T+mnyfDcHpWKSZ+tpQSGv9ahk=

</pre></details>

#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_auto_type_info = 1
g:go_fmt_fail_silently = 1
g:go_list_type = 'quickfix'
g:go_highlight_extra_types = 1
g:go_highlight_operators = 1
g:go_highlight_function_calls = 1
g:go_highlight_fields = 1
g:go_highlight_variable_declarations = 1
g:go_highlight_variable_assignments = 1
g:go_highlight_function_parameters = 1
g:go_addtags_transform = 'camelcase'
g:go_highlight_functions = 1
g:go_highlight_types = 1
g:go_fmt_command = 'goimports'
g:go_jump_to_error = 1
g:go_loaded_gosnippets = 1
g:go_highlight_generate_tags = 1
g:go_highlight_build_constraints = 1
g:go_loaded_install = 1
</pre></details>

#### filetype detection configuration:
<details><summary>filetype detection</summary><br><pre>
filetype detection:ON  plugin:ON  indent:ON
</pre></details>

**Comment by palsivertsen** [comment]
The first word in documentation comments should also be excluded, if possible.

Example from [http/server.go](https://golang.org/src/net/http/server.go)
![image](https://user-images.githubusercontent.com/11890143/96717085-3df69080-13a6-11eb-8133-793b133d98d4.png)

**Comment by bhcleek** [comment]
The highlighting of the import paths shouldn't be happening; that seems like a legit bug. Hypothetically, you should be able to disable spell checking in all strings (see `:help g:go_highlight_string_spellcheck`)  to get rid of this for now, but that seems to not be working either and even if it were, it might be more impactful than you'd be comfortable with. 🤔 

In order to accomplish not highlighting identifiers in comments, the best that could be done here is to create a tool that writes the names of all the package level identifiers in every package and writes those to a spellfile (see `:help 'spellfile'`). Even then, though, you'd have spelling errors highlighted in comments because it's so common to use identifiers that are not actual words. You'd also end up with misspellings _not_ being flagged when they should be when an identifier from one package is a misspelling of a word in your comment.

I'll leave this open, because `let g:go_highlight_string_spellcheck=0`  does not seem to be working as it should and imports are being highlighted when `let g:go_highlight_string_spellcheck=1`.

**Comment by bhcleek** [comment]
`let g:go_highlight_string_spellcheck=0` is working as expected (I was using `-c` instead of `--cmd` to set it on the commandline), so it's an option for you to leverage now if you want.
