### ISSUE TITLE
Option to disable 'main redeclared in this block' warning

### ISSUE THREAD

**Issue by laoshaw** [fatih/vim-go#3064]
for Go beginners it's handy to write many small go main functions and build/run each of them under the same directory, the only problem is the 'main redeclared in this block' warning, is it possible to make a flag so I can turn it off?

**Comment by bhcleek** [comment]
That message comes from Go, not from vim-go. What vim-go command are you running?

**Comment by laoshaw** [comment]
I was just typing go code I think, it just suddenly pops up while vim is at idle with go code in the window, a few ESC and :w will eventually make it go away. I will pay more attention when it recurs and see how to reproduce.

**Comment by bhcleek** [comment]
This doesn't sound like a vim-go issue; it sounds more like an ale issue.

However, what the message you're seeing from ale is correct; you've redeclared a function and it is properly warning you about that fact.

**Comment by WhoIsSethDaniel** [comment]
One thing you can do is place 
```
// +build ignore
[...empty line...]
```
at the top of the files you don't want to build.  This way the error will go away since 'go build' will not be trying to build those files.
The comment shown above needs to be above the package declaration and the empty line is important too.

Back when I was learning Go this worked for me.

**Comment by laoshaw** [comment]
that ignore trick does not work somehow but thanks. I'm closing this since it is not a vim-go issue.
