### ISSUE TITLE
GoImpl not work in  package main

### ISSUE THREAD

**Issue by zdmgmail** [fatih/vim-go#3084]
### What did you do?

I have two files in a dir(main) , ` a.go, a_test.go`

a.go and a_test.go have `package main` ,  

in a_test.go, use `GoImpl main.interfacename` (the interfacename is a interface in a.go  will get `vim-go: unrecognized interface: main.interfacename`

if I change `package main` to `package othermain` , `GoImpl othermain.interfacename` still get  `vim-go: unrecognized interface: main.interfacename`

then I change dirname main to othermain,  `GoImpl othermain.interfacename` work ok

then if I create `b.go` in this dir, add `func main(){}` in b.go and use `GoImpl other.interfacename`   again, get this error:

```
vim-go: interface other.interfacename not found: couldn't find package ...
```

### What did you expect to happen?

work ok with package main or about main

**Comment by bhcleek** [comment]
Vim-go is delegating to [`impl`](https://github.com/josharian/impl) here. Vim-go is passing the correct arguments to `impl` and the errors you're seeing are ultimately coming from [`impl`](https://github.com/josharian/impl). However, at least some of these situations are handleable by you.

You described three separate situations. I'll cover each of them separately for you.

> in a_test.go, use `GoImpl main.interfacename` (the interfacename is a interface in a.go will get `vim-go: unrecognized interface: main.interfacename`

Use the import path here, not just `main`. e.g. `:GoImpl github.com/zdmgmail/repo.interfacename`.

> if I change package main to package othermain , `GoImpl othermain.interfacename` still get `vim-go: unrecognized interface: main.interfacename`

Use the import path here, too. This is likely a bug in `impl`,  though, because when you change the package name to match the directory name, the implementation is generated correctly when the package name is used. Feel free to open an issue in https://github.com/josharian/impl; this seems outside the control of vim-go.

> then if I create b.go in this dir, add func main(){} in b.go and use GoImpl other.interfacename again, get this error:

The package name here should not be `other`, it should be `othermain` according to the sequence of steps that you provided, so I think this one was just user error.

**Comment by zdmgmail** [comment]
> Vim-go is delegating to [`impl`](https://github.com/josharian/impl) here. Vim-go is passing the correct arguments to `impl` and the errors you're seeing are ultimately coming from [`impl`](https://github.com/josharian/impl). However, at least some of these situations are handleable by you.
> 
> You described three separate situations. I'll cover each of them separately for you.
> 
> > in a_test.go, use `GoImpl main.interfacename` (the interfacename is a interface in a.go will get `vim-go: unrecognized interface: main.interfacename`
> 
> Use the import path here, not just `main`. e.g. `:GoImpl github.com/zdmgmail/repo.interfacename`.
> 
> > if I change package main to package othermain , `GoImpl othermain.interfacename` still get `vim-go: unrecognized interface: main.interfacename`
> 
> Use the import path here, too. This is likely a bug in `impl`, though, because when you change the package name to match the directory name, the implementation is generated correctly when the package name is used. Feel free to open an issue in https://github.com/josharian/impl; this seems outside the control of vim-go.
> 
> > then if I create b.go in this dir, add func main(){} in b.go and use GoImpl other.interfacename again, get this error:
> 
> The package name here should not be `other`, it should be `othermain` according to the sequence of steps that you provided, so I think this one was just user error.

sorry for my spelling mistake, b.go should be

```
package main

func main() {
}
```

then  use use GoImpl othermain.interfacename in a_test.go again get this error: 

```
vim-go: interface othermain.interfacename not found: couldn't find package ...
```

**Comment by bhcleek** [comment]
You can't have multiple packages in the same directory, so having `a.go` with `package othermain` and `b.go` with `package main` isn't going to work. 

When you're in a main package and you want to implement an interface from that main package, you'll need to specify the fully qualified import path for the package until josharian/impl#38 is merged.
