### ISSUE TITLE
Seems like the commands are not loaded

### ISSUE THREAD

**Issue by ethervoid** [fatih/vim-go#310]
Hello,

I'm trying to use vim-go but the only commands that I can execute are GoErrCheck, GoInstallBinaries and GoUpdateBinaries. 

I think the problem may be in the autoload. I'm using NeoBundle to load plugins. Until now I didn't have any problem.

Where can I start looking to solve this issue?

Thank you :)

**Comment by fatih** [comment]
I've tested it with Pathogen and Vundle and it worked for those. I think you shouldn't do much for Neobundle either. Check this for an example https://github.com/Mange/dotfiles/blob/master/vim/bundles.vim (just googled). It seems `ftplugin/go/*` files are not sourced. Those are sourced if Vim detects that your file is a go file. I think your setup is broken, otherwise I would receive tons of errors that it doesn't work with Neobundle.

**Comment by ethervoid** [comment]
After searching extensively I found the problem. I wasn't calling `filetype plugin indent on` and all the ftplugin wasn't loading.

Thanks

**Comment by fatih** [comment]
Awesome news @ethervoid :+1: Glad you find the solution for it :)
