### ISSUE TITLE
Go Diagnostics Highlights even when explicitly disabled

### ISSUE THREAD

**Issue by abraithwaite** [fatih/vim-go#3118]
### What did you do? (required: The issue will be **closed** when not provided)

I opened a new Go file and saw highlighting I didn't recognize or expect after upgrading vim-go from 1.21 to 1.24

### What did you expect to happen?

I expect the Go Diagnostics highlighting to not appear when I open a Go file if the setting is disabled.

### What happened instead?

Diagnostic highlighting was appearing in the go file, even though it should be disabled.

#### vim-go version:

v1.21 does not have the issue.
v1.22 does have the issue, as does v1.23 and v1.24.

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary><br><pre>
"Start pathogen
runtime bundle/pathogen/autoload/pathogen.vim
execute pathogen#infect()

syntax on
filetype plugin indent on
colorscheme molokai

set number " Show line numbers
set tabpagemax=100 "Tabpages
set showmatch " Highlight matching close symbol
set ai "autoindent
set laststatus=2
set backspace=2

set list
set listchars=tab:▸\ ,eol:¬

let g:go_highlight_functions = 0
let g:go_highlight_methods = 0
let g:go_highlight_structs = 0
let g:go_fmt_command = "golines"
let g:go_addtags_transform = "camelcase"
let g:go_fmt_options = {
    \ 'golines': '-m 128',
    \ }
let g:go_diagnostics_level = 0
</pre></details>

#### Vim version (first three lines from `:version`):

```
:version
NVIM v0.4.4
Build type: Release
LuaJIT 2.0.5
```

Happens also for normal vim:
```
:version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Nov 15 2020 16:46:37)
Included patches: 1-1989
Compiled by Arch Linux
```

#### Go version (`go version`):

```
14:19:56 $ go version
go version go1.15.6 linux/amd64
```

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

14:21:18 $ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/abraithwaite/.cache/go-build"
GOENV="/home/abraithwaite/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/abraithwaite/Projects/golang/pkg/mod"
GOOS="linux"
GOPATH="/home/abraithwaite/Projects/golang"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build367167252=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>
14:51:11  $ gopls version
golang.org/x/tools/gopls v0.6.0
    golang.org/x/tools/gopls@v0.6.1 h1:vD171EDBkyUVyp9B45IYXklV/VEfbHgX0FKw0Q0dO30=
</pre></details>

Tracked down to this change (I believe is what added it):

https://github.com/fatih/vim-go/pull/2569

Screenshots of the issue.  Happens with syntax on and syntax off.  There's a slight delay after opening the file before the highlights get applied, and sometimes (not always) the highlighting disappears after writing the buffer to disk.

![Screenshot from 2020-12-20 14-04-47](https://user-images.githubusercontent.com/3791413/102722450-274db680-42cf-11eb-9c89-0c4cc78f2495.png)
![Screenshot from 2020-12-20 14-04-28](https://user-images.githubusercontent.com/3791413/102722451-274db680-42cf-11eb-9922-42bb87439e33.png)

Let me know what other info would help.  I'm woefully ignorant when it comes to debugging vim issues beyond `:help`.

**Comment by bhcleek** [comment]
I can't duplicate the behavior described here. Adding `let g:go_diagnostics_level = 0` to my vimrc results in the text identified by diagnostics not being highlighted. 🤔 

FWIW, #2569 is the PR that introduced highlighting of text identified as problematic by `gopls`' diagnostics, but the code has changed since then and that PR _did not_ use `g:go_diagnostics_level`; `g:go_diagnostics_level` was introduced much later.

**Comment by abraithwaite** [comment]
Man I feel like a goof.  Looks like I confused the doc versions.  I believe I was reading the master branch's docs, which haven't actually been released yet.  Setting `g:go_highlight_diagnostic_warnings = 0` does the trick.

Any idea how to change the color btw?  Doesn't seem to correspond with my colortheme, although it might be pulling from there still I suppose.

Using this script:
https://vim.fandom.com/wiki/Identify_the_syntax_highlighting_group_used_at_the_cursor

Yields:
```
hi<> trans<goBlock> lo<>
Press ENTER or type command to continue
```

Which isn't super helpful 😅 .

**Comment by bhcleek** [comment]
> Man I feel like a goof. Looks like I confused the doc versions. I believe I was reading the master branch's docs, which haven't actually been released yet. Setting g:go_highlight_diagnostic_warnings = 0 does the trick.

The master docs haven't been released, but you may find a more desirable experience by using `g:go_diagnostics_enabled` or just `g:go_diagnostics_ignore_warnings` if you want to keep the highlighting of errors but not warnings.

`g:go_highlight_diagnostic_warnings` will work similarly to how `g:go_diagnostics_ignore_warnings` works. I'll avoid going into specifics about `g:go_highlight_diagnostic_warnings`, `g:go_diagnostics_ignore_warnings`, and `g:go_diagnostics_enabled`/`g:go_diagnostics_level`, because I realized while looking at code to help you that there's a bug that I need to resolve that will invalidate any detailed explanation I might provide here.

https://github.com/fatih/vim-go/pull/3052 introduced `g:go_diagnostics_level`

> Any idea how to change the highlight color btw? Doesn't seem to correspond with my colortheme, although it might be pulling from there still I suppose.

They will correspond with your colorscheme. They use the `SpellRare` and `SpellBad` syntax groups by default (see https://github.com/fatih/vim-go/blob/master/syntax/go.vim#L393-L394), but you can can customize them by defining the syntax highlighting for `goDiagnosticWarning` and `goDiagnosticError` groups in your vimrc or a `after/syntax/go.vim` file.

>Using this script:
https://vim.fandom.com/wiki/Identify_the_syntax_highlighting_group_used_at_the_cursor
> ... snip ...
> Which isn't super helpful 😅 .

That would work for traditional syntax highlighting, but the diagnostics use Vim's text properties so the position of the highlighted text changes as you're editing the file.

**Comment by abraithwaite** [comment]
Thanks for sharing this!  So much more I need to learn about vim internals 😅 

Thanks again and happy new year!
