### ISSUE TITLE
Can just keep the syntax highlighting and separate a subproject?

### ISSUE THREAD

**Issue by NGPONG** [fatih/vim-go#3121]
### What did you do? (required: The issue will be **closed** when not provided)

There is no doubt that this plugin is the best tool for golang developers, I like it a lot, but it is too heavy.

In fact, I've already done some of the features that vim-go already has through some other means, and now I only have syntax highlighting left. If I use this plugin when I only want syntax highlighting, there are a lot of features that conflict with what I've already done

So, if possible, I would suggest separating a separate subproject for the purpose of syntax highlighting, I know it seems selfish, why don't I implement it myself? The main reason is that learning vim script is time-consuming, and secondly, I checked the existing projects on github and I found that none of the plugins provide syntax highlighting that is comparable to vim-go, which is, in short, vim-go is perfect!

**Comment by bhcleek** [comment]
> There is no doubt that this plugin is the best tool for golang developers, I like it a lot, but it is too heavy.

Thank you. What do you mean by "too heavy"?

> In fact, I've already done some of the features that vim-go already has through some other means, and now I only have syntax highlighting left. If I use this plugin when I only want syntax highlighting, there are a lot of features that conflict with what I've already done

> What kind of conflicts do you see?

> So, if possible, I would suggest separating a separate subproject for the purpose of syntax highlighting, I know it seems selfish, why don't I implement it myself? The main reason is that learning vim script is time-consuming, and secondly, I checked the existing projects on github and I found that none of the plugins provide syntax highlighting that is comparable to vim-go, which is, in short, vim-go is perfect!

> I don't see that happening soon, but it's not __too__ hard to bring to fruition. I'll consider it. 

The landscape has definitely changed a lot since vim-go was first conceived. I'll be curious to know what parts you find to be too heavy and what is conflicting with other plugins for you; that information would be very helpful when deciding what would need to be done to turn some of those features off. It's also possible that there's already features available in vim-go that would satisfy your concerns.

**Comment by NGPONG** [comment]
> > There is no doubt that this plugin is the best tool for golang developers, I like it a lot, but it is too heavy.
> 
> Thank you. What do you mean by "too heavy"?
> 
> > In fact, I've already done some of the features that vim-go already has through some other means, and now I only have syntax highlighting left. If I use this plugin when I only want syntax highlighting, there are a lot of features that conflict with what I've already done
> 
> > What kind of conflicts do you see?
> 
> > So, if possible, I would suggest separating a separate subproject for the purpose of syntax highlighting, I know it seems selfish, why don't I implement it myself? The main reason is that learning vim script is time-consuming, and secondly, I checked the existing projects on github and I found that none of the plugins provide syntax highlighting that is comparable to vim-go, which is, in short, vim-go is perfect!
> 
> > I don't see that happening soon, but it's not **too** hard to bring to fruition. I'll consider it.
> 
> The landscape has definitely changed a lot since vim-go was first conceived. I'll be curious to know what parts you find to be too heavy and what is conflicting with other plugins for you; that information would be very helpful when deciding what would need to be done to turn some of those features off. It's also possible that there's already features available in vim-go that would satisfy your concerns.


Thanks for your response! 

About

> What kind of conflicts do you see?

As of now and in my point, it seems that the vim-go Intellisense engine conflict with **coc.nvim**, which also uses **gopls** as a language-server

Maybe there are some other functions that are inseparable from gopls that conflict with coc.nvim, I don't know, but at least in terms of experience, there should be a conflict with the intelligent complementary features

**Comment by bhcleek** [comment]
What conflicting behavior are you seeing?

**Comment by NGPONG** [comment]
I'm sorry it's taken so long to respond because of the recent busy.

So, What I'm about to say below you may think I'm very picky, yep, most people in my life would comment on me that way too, anyway, let's get started!

<br/>

1. I don't understand why the msg box below prompts this thing every time when I finished a smart fill(just like vscode when type `Tab` or `Enter`), and I must admit it's annoying.

![微信截图_20201227214422](https://user-images.githubusercontent.com/38415769/103172353-cbb29880-488d-11eb-953a-7b048b5f110b.png)

![微信截图_20201227213656](https://user-images.githubusercontent.com/38415769/103172354-cd7c5c00-488d-11eb-89ba-d9717c485671.png)

<br/>

2. When I import a package that I haven't used yet, coc.nvim works well with gopls to prompt me for `package import but not used`, but when I save the file, the prompt disappears, maybe there is a conflict with the auto-formatting feature when saving? I don't know.

![微信截图_20201227213758](https://user-images.githubusercontent.com/38415769/103172425-4ed3ee80-488e-11eb-8f48-d7dc4407c9a2.png)

![微信截图_20201227213842](https://user-images.githubusercontent.com/38415769/103172423-4380c300-488e-11eb-89d6-9722f2869d6f.png)

<br/>

3. About qucikfix list, please check the following pic.

![微信截图_20201227214342](https://user-images.githubusercontent.com/38415769/103172421-3ebc0f00-488e-11eb-8ad2-dc5eef2d73fc.png)

<br/>

There may be some other things but I haven't found them yet. So, combined with the fact that I just need `syntax highlighting`, it's really time consuming to go through and disable some of the known feature options one by one.

**Comment by bhcleek** [comment]
Most of these are easily resolved by disabling some of the features that are modifying buffers on save. You can find all of those by searching the vim-go help for `_autosave`.

> I don't understand why the msg box below prompts this thing every time when I finished a smart fill(just like vscode when type Tab or Enter), and I must admit it's annoying.

I haven't seen that before, but I think I _might_ know where it's coming from. Can you duplicate with `let g:go_debug=["lsp"]` and provide me with the full contents of the `__GOLSP_LOG__` window so I can diagnose?

> 
When I import a package that I haven't used yet, coc.nvim works well with gopls to prompt me for package import but not used, but when I save the file, the prompt disappears, maybe there is a conflict with the auto-formatting feature when saving? I don't know.

You can fully turn this off if you want by using `g:go_fmt_command` (see `:help g:go_fmt_command`). Either set it to `gofmt` _or_ set it to `gopls` and make sure to also turn off `g:go_imports_autosave'` (see `:help g:go_imports_autosave`). `g:go_imports_autosave` is turned off by default, so you could also just make sure it's not set at all in your vimrc or after files.

> About qucikfix list, please check the following pic.

Yes, this is coming from formatting on save. If you want to turn that off, you can use `g:go_fmt_autosave` (see `:help g:go_fmt_autosave`)

> Sometimes it makes the error message that coc.nvim can prompt well disappeared, I'm not quite sure how to trigger this problem.

I'm not sure what you mean by this. Can you clarify?

It might be explained by the same root cause as the third item you mentioned; when either `g:go_fmt_command` is set to `'goimports'` and `g:go_fmt_autosave` is set or `g:go_imports_mode` is set and `g:go_imports_autosave` is set, then any unused imports will be removed on save.

**Comment by bhcleek** [comment]
@NGPONG should we close this? I'm happy to leave it open and continue the conversation if want...

**Comment by NGPONG** [comment]
I'm sorry it's taken so long to respond again.. haha

Your answer solved most of the problems, Anyway, I'm satisfied with the current state and I'm not going to focus on it.
