### ISSUE TITLE
syntax highlighting not working for me

### ISSUE THREAD

**Issue by luck02** [fatih/vim-go#316]
It was working IIRC, however opened a .go file and *poof* no syntax highlighting.

Not sure what happened.

I set
:set syntax=on
:set filetype=go

and I got a little highlighting (green func call and blue strings).  But definitly not complete.

YCM is still working and I can run :GoIMports etc.

**Comment by fatih** [comment]
Some of the options are disabled because they syntax highlighting is slow on slow machines. To enable them add these to your vimrcs:

```viml

let g:go_highlight_structs = 1 
let g:go_highlight_methods = 1
let g:go_highlight_functions = 1
let g:go_highlight_operators = 1
let g:go_highlight_build_constraints = 1

```

Check out the doc for even more options to enable/disable:

https://github.com/fatih/vim-go/blob/master/doc/vim-go.txt#L502

Also sometimes you need to call `:set syntax=enable`, especially of Vim GUI's, but I think your problem is the one I've listed above. I'll add this to the FAQ, because I've received a lot of issues like this.

**Comment by luck02** [comment]
Awesome, thanks.  that resolved it.

G
