### ISSUE TITLE
Syntax highlighting only

### ISSUE THREAD

**Issue by 89z** [fatih/vim-go#3163]
I only care about the highlighting, nothing else. So I got this file:

https://github.com/fatih/vim-go/blob/master/syntax/go.vim

and copy to my local Vim install. However I get these errors:

~~~
Unknown function: go#config#FoldEnable
~~~

I checked the notes here:

https://github.com/fatih/vim-go/blob/755b498c7604e7aee4d001d2a78c2d1e079eb8d5/doc/vim-go.txt#L2611-L2622

but I am not sure how to implement the suggestions that are being made.

**Comment by bhcleek** [comment]
You're looking for options like `g:go_fmt_autosave` (`:help g:go_fmt_autosave`).

**Comment by 89z** [comment]
ok, but what are you talking about? Do I need to add that to `.gvimrc`? If so what value do I give it?

**Comment by bhcleek** [comment]
You'd use vim-go (not just the syntax file) and add `let g:go_fmt_autosave = 0` and other options to your `.vimrc`.

**Comment by 89z** [comment]
I only want to use the syntax file...

**Comment by bhcleek** [comment]
> but I am not sure how to implement the suggestions that are being made.

You implement those suggestions by installing vim-go and setting options to disable some of the features so you can have the Vim experience you're looking for.

> I only want to use the syntax file...

You're free to use only the syntax file, but you'll need to either also copy the bits of vim-go that the syntax file depends on or modify the syntax file to your liking in your copy.

**Comment by 89z** [comment]
https://github.com/fatih/vim-go/issues/3295

**Comment by bhcleek** [comment]
@89z why did you reopen this? What more do you need?

You may be interested to know that since https://github.com/vim/vim/commit/90df4b9d423485f7db16e3a65cab4f14edc815ae#diff-ba1f661313ce15c6dbaad5f0d3969dfda150d4a6e56ebf2fc3e25643fe2b15dd, Vim itself has vim-go's syntax highlighting by default.

**Comment by 89z** [comment]
@bhcleek `vim/vim` does use `fatih/vim-go` now, but I dont like the color `fatih/vim-go` uses, as I mention in another issue. So I tried to change the color via `vimrc`, but that didnt work because I am using `NLKNguyen/papercolor-theme` colorscheme. I also tried forking `fatih/vim-go` to change the color, but that also failed because of this issue.

So until something changes, I am kind of stuck. I am currently using `google/vim-ft-go` because the issue on this page, as the other repo allows you to use just the copy paste the syntax file and it just works, while this repo wants you to use a bunch of other crap that I dont care about.

I would prefer to use `fatih/vim-go`, either the `vim/vim` version or from this repo directly. But with all the problems I described, I dont know how to make it work.

**Comment by bhcleek** [comment]
If papercolor-theme isn't coloring the highlight groups to your liking, then your complaint is with the colorscheme, not with vim-go.

Stepping back and reading about colorschemes, syntax files, and highlight groups may be useful for you. You can find all the information you need in the Vim help about those two topics. Very quickly, though: colorschemes define which colors should be used for highlight groups. Syntax files define which highlight groups should be used for regions of text.

**Comment by 89z** [comment]
The problem is, that `fatih/vim-go` considers `nil` a `Boolean`, while `google/vim-ft-go` considers `nil` a `Keyword`. So messing with the colorscheme isnt going to help anything.

I am fine with the colors that `NLKNguyen/papercolor-theme` uses for `Boolean` and `Keyword`. I am not fine with Go `nil` being a `Boolean`, as I dont like that color.

**Comment by bhcleek** [comment]
Do you have a request for vim-go? It sounds like you'd prefer to not use vim-go at all; you neither want its syntax nor its other features, so I'm not sure what you're asking for.

**Comment by 89z** [comment]
Yeah, it would be helpful if you could just copy the syntax file here into the runtime directory. Several other Vim repos offer this, so I dont think its a crazy request. FYI this is also the title of the issue, and is described in the original issue.

**Comment by bhcleek** [comment]
As I mentioned in https://github.com/fatih/vim-go/issues/3163#issuecomment-922368816, Vim's syntax file now effectively comes from vim-go. If what you want is vim-go's syntax file without the need to install vim-go, then Vim's syntax file for Go is what you want.

FWIW, this isn't true:
> The problem is, that fatih/vim-go considers nil a Boolean

Vim-go uses the `goPredefinedIdentifier` for `nil`.

If you don't like the way that your color scheme styles `Boolean`, then as we discussed previously, you can use your vimrc to style the `goPredefinedIdentifier` highlight group differently than as a `Boolean`.

**Comment by 89z** [comment]
I already said that doesnt work, because colorscheme overrides and/or ignores the `vimrc` setting

**Comment by bhcleek** [comment]
Something else must be going on; it's highly unlikely that the colorscheme is modifying the highlight groups for Go colors, and the technique I mentioned earlier works.

**Comment by 89z** [comment]
I dont know what to tell you. If I have this in my `vimrc`:

~~~vim
colorscheme PaperColor
~~~

then any command like you put is ignored, regardless if said command comes before or after the colorscheme command

**Comment by bhcleek** [comment]
Do you see the same problem when you use other colorscheme?

**Comment by 89z** [comment]
If I use the default colorscheme (no entry in `vimrc`), then command like you put are recognized

**Comment by bhcleek** [comment]
What exactly did you put in your vimrc and how does the PaperColor colorscheme style those groups?

**Comment by 89z** [comment]
> What exactly did you put in your vimrc

~~~vim
colorscheme PaperColor
filetype indent off
filetype plugin off
let &background = 'light'
let &clipboard = 'unnamed'
let &colorcolumn = 81
let &columns = 84
let &directory = $TMP
let &encoding = 'UTF-8'
let &expandtab = 1
let &fileformats = 'unix'
let &guifont = 'Consolas:h12'
let &guioptions = 'r'
let &hlsearch = 1
let &ignorecase = 1
let &linebreak = 1
let &number = 1
let &shiftwidth = 3
let &smartcase = 1
let &softtabstop = 3
let &virtualedit = 'onemore'
let &wrap = 0
~~~

> how does the PaperColor colorscheme style those groups?

I dont know. The source code is here:

https://github.com/NLKNguyen/papercolor-theme/blob/master/colors/PaperColor.vim

**Comment by bhcleek** [comment]
There's no highlight setting in what you provided above.

**Comment by 89z** [comment]
I already said, that I tried your exact command:

~~~vim
hi link goPredefinedIdentifiers Keyword
~~~

I tried putting it before and after the colorscheme command. In both cases, the highlight command was ignored.

**Comment by 89z** [comment]
OK correction. I think I was doing something wrong, as it is working now.

Sorry about that. However the original issue still remains.

I understand that `vim/vim` Go file is a drop in file, but it would be nice if the syntax file here was drop in as well. Currently its not, as it breaks with missing function errors as details in the original post.

**Comment by bhcleek** [comment]
The vim syntax file gives you everything you want, as it was recently synchronized with the vim-go syntax file.

The syntax file in vim-go is not going to be changed to support the use case you're asking for. The vim syntax file will continue to be updated periodically, though, to get any fixes that may get applied to the vim-go syntax file.

**Comment by 89z** [comment]
> The vim syntax file gives you everything you want, as it was recently synchronized with the vim-go syntax file.

That wont always be the case though. Cases could arise where I, or someone else wants to use a feature thats upstream, and hasnt been merged with `vim/vim` yet. Vim has historically been pretty slow with updates, so its not unreasonable to want to use the upstream version for any number of reasons.

> The syntax file in vim-go is not going to be changed to support the use case you're asking for.

Thats too bad. I maintain that the ability to have a drop in syntax file is a useful feature. Some people dont need or care about anything other than syntax, so to force that upon everyone (even moreso since its now the default Vim Go syntax), is not cool.

**Comment by bhcleek** [comment]
Considering that I supplied the last update to the Go syntax file in Vim, that it previously came from vim-ft-go and hadn't been updated in Vim for quite some time, that my update was taken relatively quickly, and that there are very infrequent changes to the vim-go syntax file, I don't share your concern.

**Comment by 89z** [comment]
> Considering that I supplied the last update to the Go syntax file in Vim, that it previously came from vim-ft-go and hadn't been updated in Vim for quite some time, that my update was taken relatively quickly, and that there are very infrequent changes to the vim-go syntax file, I don't share your concern.

Credit where credits due. Throughout this issue and others, youve been patient, helpful and respectful. Thanks for that.

However lets be real, all the the above that Ive quoted, those are just rationalizations. The home for Vim Go is **here**, not at `vim/vim`. So it doesnt really hold water to say "take your problems to `vim/vim`", when concerns should be address here first, then pushed downstream as needed, not the reverse. Not to mention, you havent said a word about pull requests. So am I to assume, that even if I worked up a pull request with the proposed change, it would be rejected? Another thing I noticed, is that you havent seemed to provide a single reason for the decision, other than "its not going to happen", or "just use `vim/vim`.

If you reason is "I just dont want it to happen, and Im in charge", fair enough. But at least be up front and honest about it.

**Comment by bhcleek** [comment]
> Credit where credits due. Throughout this issue and others, youve been patient, helpful and respectful. Thanks for that.

Thanks.

> those are just rationalizations

I disagree. They're not [rationalizations; they're valid counter arguments grounded in experience instead of hypothetical fears.

If you really want to split the syntax out, I'm pretty sure that you can copy `autoload/go/config.vim` and `syntax/go.vim` to your runtimepath and get what you're looking for. I believe that's how polyglot does it when it vendor's vim-go's syntax file.

>  it doesnt really hold water to say "take your problems to vim/vim"

I don't think I've said any such thing. I pointed out that the file you're looking for is already in Vim and you could get it from there if you wish.

My reasons for not doing what you're asking is multi-faceted. Some of them are stronger than others, but here they are in no particular order:
1. The settings for vim-go are maintained in a single file, `autoload/go/config.vim` for consistency throughout the vim-go codebase to ease maintainability.
2. While the relevant portions of vim-go's syntax file are now upstreamed to Vim as needed, vim-go does not claim to be suitable for all Go developers and whatever their personal preferences may be, nor would I expect to craft _any_ codebase for ease of excision into other systems. The syntax file it provides is part of vim-go and should be consistent with the rest of the vim-go codebase. My ordered priorities for vim-go are: [ease of use, use of maintainability, and then ease of implementation](https://twitter.com/bhcleek/status/979445479606898688?s=20). Simplifying forking or excision doesn't make the list.
3. The go syntax file from vim provides what you want, and the syntax file in vim-go very rarely changes anymore; it's pretty stable and I expect it will remain so. There just isn't much reason to assume otherwise.
4. I don't feel any need to support users that don't want all of vim-go based on some misunderstanding about how Vim plugins work (FWIW, I'm not saying anything one way or the other about your understanding of Vim plugins). Usually, when someone asks for this, it's because they mistakenly believe that installing vim-go fully will somehow affect the performance of their system when they in fact only want the syntax files. Vim-go fully supports disabling `gopls` and the various autosave settings that it has.
5. If one does that (☝️) small bit of configuration, then one gets all the benefits of the vim-go syntax file, and I don't see any reason to do work simply because some potential users wish for a slightly different experience that's based purely on their personal preferences.

> But at least be up front and honest about it.

Hah! People that know me IRL know that being upfront and honest is something I can be counted on to provide. 😆

**Comment by bhcleek** [comment]
To put your mind at ease somewhat regarding our ability to make changes to syntax file included with Vim, you might be interested to know that I submitted a PR yesterday, and it's already accepted: https://github.com/vim/vim/pull/8894

**Comment by 89z** [comment]
Please stop commenting on this thread, or I will unsubscribe. Youre not going to convince me that not supporting drop-in syntax file is a good idea. I am just going to continue vendoring `google/vim-ft-go`, until `fatih/vim-go` implements drop-in syntax support.

If that never happens, then I will never use `fatih/vim-go` again, either the builtin or upstream.

**Comment by bhcleek** [comment]
That's quite the interesting take given that you seem to have deleted all of your comments on this issue and on #3295.

I'll leave my comments up here so that others may see them in case they have similar requests as what started this issue and this comment so that it's this wasn't a set of serial rants on my part.

I'm also locking this issue.
