### ISSUE TITLE
GoFmt marks unmodified buffer as modified

### ISSUE THREAD

**Issue by ebfe** [fatih/vim-go#317]
Every invocation of GoFmt results in the buffer being marked as modified even if GoFmt didn't change anything. 

```
:GoFmt
:w
:set modified?
nomodified
:GoFmt 
// nothing actually changed, but
:set modified?
  modified
```

It would be nice to detect if GoFmt actually changed the buffer.

**Comment by fatih** [comment]
The weird thing is, if you run `:w`, it'll invoke `GoFmt`. However it doesn't mark it as modified. Only if you call `GoFmt` manually will it mark it as modified. I'll look into this and let you know when I find something.

**Comment by fatih** [comment]
Alright I know why (actually it was always like this, but your example with `w` confused me :))

GoFmt changes the buffer always, regardless the change it has or not. It'll replace the whole content with the content from GoFmt. So, if your code is already formatted, it goes and replaces it with the GoFmt output, and because they are identical it seems it's not modified, but under the hood it is. So it's totally normal that Vim shows that it's modified, because it's really modified. 

Checking if the file is formatted before would introduce another step into the formatting process, which would slow it down. Thanks for bringing it up though.
