### ISSUE TITLE
GoDef not working inside ~GOPATH/pkg/mod

### ISSUE THREAD

**Issue by thefuga** [fatih/vim-go#3235]
### What did you do? (required: The issue will be **closed** when not provided)

After updating vim-go, `:GoDef` is not working properly anymore, especially inside `go/pkg/mod`.
When running `:GoDef` to a mod dependency takes me to the definition. Running `:GoDef` again inside the following package raises an error.
### What did you expect to happen?
It was expected that any `:GoDef` call would take me to the definition.
### What happened instead?
The following error occurs:
```
vim-go: : packages.Load error
```

Calling `:messages`, this is reported:
```
vim-go: [definition] SUCCESS
"~/go/pkg/mod/gopkg.in/!data!dog/dd-trace-go.v1@v1.30.0/ddtrace/tracer/tracer.go" [readonly] 406L, 12211B
vim-go: [definition] FAIL
vim-go: err: exit status 1: stderr: go: github.com/DataDog/datadog-go@v4.4.0+incompatible: missing go.sum entry; to add it:
vim-go:         go mod download github.com/DataDog/datadog-go
vim-go: : packages.Load error
```

The example is from the Datadog package, but it happens with any package inside the mod dir.
### Configuration (**MUST** fill this out):
The standard configurations are being used.

#### vim-go version:
Probably the latest. I'm not sure how to check this.

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary>
These are the parts that may be related to `vim-go`

```vim
set nocompatible "be iMproved, required
filetype off "required

set rtp+=~/.vim/bundle/Vundle.vim
call plug#begin()
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }
call plug#end()

let g:coc_global_extensions = get(g:, 'coc_global_extensions', ['coc-snippets', 'coc-pairs', 'coc-phpls', 'coc-eslint']) 

autocmd FileType go setlocal shiftwidth=4
autocmd FileType go setlocal tabstop=4

let g:go_fmt_command = "goimports" 
let g:go_def_mode="gopls"
```
</details>

#### Vim version (first three lines from `:version`):

Vi IMproved 8.2
#### Go version (`go version`):

1.16.4

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

v0.6.10
</pre></details>

**Comment by bhcleek** [comment]
It looks like `gopls` is having a problem because of 
```
vim-go: err: exit status 1: stderr: go: github.com/DataDog/datadog-go@v4.4.0+incompatible: missing go.sum entry; to add it:
vim-go:         go mod download github.com/DataDog/datadog-go
```

I'd try clearing the module cache (`go clean -modcache`) and try again.

I can't duplicate this on my machine. I wonder if it may have something to do with the `go` directive if your `go.mod` file; what version do you have there?

I tried duplicating this by using the example provided in `github.com/DataDog/datadog-go` and jumping from the `main.go` file into `github.com/DataDog/datadog-go@v4.4.0+incompatible` and jumping around inside of that.

**Comment by thefuga** [comment]
I've tried cleaning the mod cache but the issue continues.
Dug a little bit further and looks like this only happens with packages that have multiple files within the same package and the definition is in the same package but in another file.

**Comment by bhcleek** [comment]
Ok, I can duplicate that. I suspect that the problem here is actually in `dd-trace-go` due to the `go.sum` file missing some expected entries. You can duplicate that for yourself by cloning dd-trace and running `go mod tidy` there; you'll see that `go.sum` gets populated with a lot of missing entries. Similarly, the `go.mod` file gets a lot of new entries, too.

This seems like an issue to raise with Datadog in their dd-trace repository.

Here are the relevant logs from `gopls` (`:let g:go_debug['lsp']` in vim-go)

```
===== sent =====
Content-Length: 239

{"method":"textDocument/definition","jsonrpc":"2.0","id":7,"params":{"textDocument":{"uri":"file:///Users/bhcleek/go/pkg/mod/gopkg.in/%21data%21dog/dd-trace-go.v1%40v1.31.0/ddtrace/tracer/tracer.go"},"position":{"character":29,"line":93}}}
===== received =====
Content-Length: 243

{"jsonrpc":"2.0","error":{"code":0,"message":"err: exit status 1: stderr: go: github.com/DataDog/datadog-go@v4.4.0+incompatible: missing go.sum entry; to add it:\n\tgo mod download github.com/DataDog/datadog-go\n: packages.Load error"},"id":7}
===== received =====
Content-Length: 503

{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":1,"message":"2021/05/24 12:10:04 go/packages.Load: err: exit status 1: stderr: go: github.com/DataDog/datadog-go@v4.4.0+incompatible: missing go.sum entry; to add it:\n\tgo mod download github.com/DataDog/datadog-go\n\n\tsnapshot=2\n\tdirectory=/Users/bhcleek/go/pkg/mod/gopkg.in/!data!dog/dd-trace-go.v1@v1.31.0\n\tquery=[file=/Users/bhcleek/go/pkg/mod/gopkg.in/!data!dog/dd-trace-go.v1@v1.31.0/ddtrace/tracer/tracer.go]\n\tpackages=0\n"}}

```

**Comment by thefuga** [comment]
Great info! I'll see if there are any related issues there. Maybe I can open a PR there.
Thank you very much for the support @bhcleek !
