### ISSUE TITLE
Entering a colon outdents the line

### ISSUE THREAD

**Issue by benbarbour** [fatih/vim-go#326]
Probably related to this: https://code.google.com/p/go/issues/detail?id=7593. I'm getting it whenever I type a colon on a line right below an if statement. For example:

```go
if err != nil {
    t.Fatalf("Error doing thing: %v", err)
}
```

As soon as I type the colon in insert mode the line is un-indented. It's a little jarring while typing. If I `:GoFmt` right after finishing the line it gets indented again.

**Comment by benbarbour** [comment]
Actually, it happens on any line where the previous line is not indented, including the first line of a function.

**Comment by fatih** [comment]
Can you give more detail please? It works for me and I don't have any problems. Recently there was a problem with someone else, and he fixed it by adding this `set smartindent` to the vimrc (of course if it's the same problem. Here are is the vimrc I'm using without any single problem, you can have a look for it: https://github.com/fatih/dotfiles/blob/master/vimrc

But I didn't understand your problem right now,  because I don't have any indentation problem.

**Comment by samuell** [comment]
This doesn't seem to be go-vim specific. See e.g:
http://vim.1045645.n5.nabble.com/Stopping-automatic-outdent-with-colon-in-C-comment-td1169568.html

**Comment by benbarbour** [comment]
Setting smartindent seems to fix it and I haven't noticed any other negative effects yet. Thanks!

**Comment by fatih** [comment]
Thanks for the feedback @benbarbour. Glad you fixed it.
