### ISSUE TITLE
Question how <Plug> command could be expanded upon need, if possible

### ISSUE THREAD

**Issue by stefanos82** [fatih/vim-go#3409]
Inside `HOME/.vim/after/ftplugin/go/gomappedkeys.vim` I have the following:

```
inoremap <buffer> <C-k> <C-x><C-o>
nmap <F5> <Plug>(go-run)
nmap <C-i> <Plug>(go-imports)
nmap <C-l> <Plug>(go-info)
```
This works of course as expected, but I would like to know whether we could execute multiple commands combined with `<Plug>(go-run)`, if possible.

I know this command `nmap <F5> :up <bar> !clear; /usr/bin/env go run %<CR>` works, but I got curious how anyone could accomplish the same with the use of `<Plug>`.

Any feedback please?

**Comment by bhcleek** [comment]
The `<Plug>` mappings can't be combined like that, because each has a `<CR>` at the end. If you wanted to do something like this, then you could put your own `<Plug>` mappings in an `after/ftplugin` directory (e.g. `after/ftplugin/go.vim` or `after/ftplugin/go/mappings.vim`). See `:help after-directory`.

**Comment by stefanos82** [comment]
I learned something new today! Cheers @bhcleek :+1:
