### ISSUE TITLE
is it possible to not set makeprg?

### ISSUE THREAD

**Issue by shaofeng66** [fatih/vim-go#3526]
### What did you do? (required: The issue will be **closed** when not provided)
is it possible to not set makeprg?

My project use a makefile which by default do a docker build, which does not work on my machine. I use ```make build``` to build on my development machine, so I have an ```autocmd FileType go autocmd BufEnter <buffer> setlocal makeprg=make\ build```

However makeprg is reset to ```make``` by vim-go every time when I save a buffer.

Any suggestion?

```
verbose set mp?
  makeprg=make
        Last set from ~/github/shaofeng66/home/.vim/pack/fatih/start/vim-go/ftplugin/go.vim line 23
```
####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary>

```vim

```
</details>

#### Vim version (first three lines from `:version`):

:version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Nov  3 2021 20:43:23)
macOS version - arm64
Included patches: 1-3070

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

</pre></details>

**Comment by bhcleek** [comment]
That's very strange. Vim-go sets`makeprg` in `compiler/go.vim`, not in `ftplugin/go.vim`. 

Vim-go's `compiler/go.vim` has this:
```
if filereadable("makefile") || filereadable("Makefile")
  CompilerSet makeprg=make
else
  CompilerSet makeprg=go\ build
endif
```

i.e. there should be no need to set up something customer, because vim-go detects that `Makefile` and sets it up for you. I can't help but wonder if your `Makefile` is in a parent directory instead of in your current working directory, and therefore it's not detected.

I've tried to test what you've described on my own machine, but I am unable to duplicate what you're seeing. Even after setting up an autocmd for the FileType event does not cause `makeprg` to be reset. Perhaps some clear steps to reproduce would be helpful?

**Comment by bhcleek** [comment]
closed for lack of feedback
