### ISSUE TITLE
Manual install not completely working

### ISSUE THREAD

**Issue by Swoogan** [fatih/vim-go#359]
My installation process:

    git clone --depth 1 https://github.com/fatih/vim-go.git
    mv vim-go ~/.vim

After that the following work: syntax highlighting, `GoInstallBinaries` and `go fmt` on exit. However, `:help vim-go`, `:GoDoc`, `:GoRun`, etc... don't work (eg: Not an editor command: GoDoc). The tools are in my $GOPATH/bin folder and I can use them from the command line.

Any ideas what I've done wrong?

**Comment by fatih** [comment]
Hi @Swoogan . You need to the whole content to `~/.vim`. This is wrong:

```
~/.vim/vim-go
```

This is right

```
~/.vim/autoload
~/.vim/plugin
...
```

That's why manual installation is not recommended. Because it will also override your other plugins if any.

I recommend that you use https://github.com/tpope/vim-pathogen It's dead simple and very easy to use.

**Comment by Swoogan** [comment]
Ah, I see my second command was ambiguous. I did not have a `~/.vim` directory. The move created it.

    swoogan@gopher:~$ ls ~/.vim
    addon-info.json  compiler  ftdetect  gosnippets  plugin     scripts
    autoload         doc       ftplugin  indent      README.md  syntax

Looking through the other issues I saw to run `:scriptnames`. Doing so shows:

    7: ~/.vim/ftdetect/gofiletype.vim
    ...
    10: ~/.vim/plugin/go.vim

And that is it from my ~/.vim folder. Should more be in there?

**Comment by fatih** [comment]
Please have a look at how to install manually plugins (which again is not recomended):

http://superuser.com/questions/404686/installing-plugins-in-vim

I don't have much time to debug it right now, it would be much better if you ask it on a Vim mail list or on Stack Overflow. Because this is a vim plugin installation problem. Sorry If I can't help much here.

**Comment by Swoogan** [comment]
Hey, no worries. I just thought if I wasn't following the manual steps right, that the instructions might be improved. It looks like that isn't the case.

I just took the manual route to keep things simple. I don't think I succeeded. Thanks for your help.

**Comment by fatih** [comment]
I'll look into it, probably I'll delete it because right now no one is using it in the vim world. My fault putting it there sorry :/ (it was not there 2 months ago).
