### ISSUE TITLE
How to setup gopath manually inside `.vimrc`

### ISSUE THREAD

**Issue by coderj001** [fatih/vim-go#3660]
`gopath` and `goroot` as i'm using goenv I have trouble running properly in vim

**Comment by bhcleek** [comment]
`goenv` is generally not needed in the Go community because of the go1 compatibility guarantee. What problem are you trying to solve with it?

Vim-go expects `go` to be in `PATH` and looks for it there.

You can set up `GOPATH` manually in your vimrc with a simple `let` statement if you really need to (e.g. `let $GOPATH="/my/go/path"`, but again, that's unlikely to be necessary. Many (most?) projects have moved on from GOPATH oriented to being Go modules; modules do not require `GOPATH`.

**Comment by coderj001** [comment]
Thanks man. You can close this issue.
