### ISSUE TITLE
How to remove left partheness when autocompleting?

### ISSUE THREAD

**Issue by demon386** [fatih/vim-go#373]
I use vim-go with YCM.

Here's a what I got when pressing TAB to select candidates when auto-completing.

![vim-go](https://cloud.githubusercontent.com/assets/1246611/6997014/6db18e36-dbdc-11e4-95c1-9d08250188e0.png)

How can I remove the left partheness when auto-completing?

**Comment by fatih** [comment]
This is how we get the result from gocode:

https://github.com/nsf/gocode/blob/master/formatters.go#L42

The `(` is attached automatically, so you can write it immediately. This is not something I want to change because everyone is relying on it and everyone is used to it already. However you can manually change the `complete.vim` (https://github.com/fatih/vim-go/blob/master/autoload/go/complete.vim) file. Change the line 157 from (in `go#complete#Complete` function) from:

```viml
return g:gocomplete_completions[1]
```

to
 
```viml
return map(copy(g:gocomplete_completions[1]), 's:trim_bracket(v:val)')
```

This would fix your problem. Maybe we can add a feature for function plumbing which changes the `word` parameter passed to vim's omnifunc. This is a very advanced feature of course, and I'm always in favor of simplicity :) Thanks for opening the PR, let me know if this fixes your problem.

**Comment by demon386** [comment]
Thanks for replying.

I get used to using plugin "delimitMate" for auto pairing partheness, so this doesn't feel natural to me.

Anyway I'll fork and customize the behavior.
