### ISSUE TITLE
No uninstall instructions

### ISSUE THREAD

**Issue by cflewis** [fatih/vim-go#381]
How do I uninstall vim-go? I deleted the package that I `git clone`d to, but it still attempts to execute. I have absolutely no idea where it's coming from.

What files does vim-go touch? How to I uninstall it forever?

**Comment by fatih** [comment]
How did you installed it? There is no uninstall instruction because if you use a plugin manager all it's is removing the repo folder. If you installed it manually (copying files) basically uninstalling is removing any files that belongs to vim-go. It's should be under `~/.vim/` folder. Of course you know the correct path because you installed it.

**Comment by held-m** [comment]
It works weirdly with vim-plug. Just `PlugClean`  doesn't work. I found the plugin installed `home/${USER}/.local/share/nvim/site/pack/plugins/start/vim-go`  After removed the directory finally it was removed.
