### ISSUE TITLE
None of the Go commands are installed

### ISSUE THREAD

**Issue by anstosa** [fatih/vim-go#414]
I installed via NeoBundle ([.vimrc](http://hastebin.com/raw/jeyelosofe)) and the only `Go*` commands available to me are `GoErrCheck`, `GoInstallBinaries`, and `GoUpdateBinaries`. Everything else returns `Not an editor command: GoDef`.

I ran `GoInstallBinaries` with my `$GOPATH` set to `~/.Go` and all the binaries were successfully installed there. `GoInstallBinaries` now does nothing. `GoUpdateBinaries` reinstalls them in the same place.
```
$ which godef
/home/ansel/.Go/bin/godef
```
I've tried reinstalling `vim-go` and everything else that I can think of. Any ideas?

**Comment by fatih** [comment]
It's not a binary issue. It's an installation issue. Your setup is imho wrong, because the Go commands are not picked up. Also commands such as `:GoDef, :GoBuild, :GoRun, etc..` are populated only when you edit a `go` file. So first please use a simple plugin such as pathogen and try it. It'll work. After that debug your vimrc, I think you have something wrong in your vimrc. I hope you also don't use any of the old vim plugin that provides Go features.

**Comment by anstosa** [comment]
Thanks @fatih.

For others that might encounter this. My specific issue was that I was setting `syntax on` before `neobundle#end()`

Not sure why this had an effect, but moving that line out fixed it.

**Comment by fatih** [comment]
Awesome to hear. :+1: :)
