### ISSUE TITLE
Can't undo just gofmt

### ISSUE THREAD

**Issue by phemmer** [fatih/vim-go#428]
Lets say I add a few lines to a file (the change is contained within a single undo history event), and then I write the file. This plugin is going to call `gofmt` on the file, and replace the buffer. It then joins this buffer-replace event with the previous item in the undo history, meaning it is not possible to press `u` and only undo the gofmt, as it is also going to undo the earlier change.

Is there any reason the changes are being squashed?

**Comment by fatih** [comment]
Hi @phemmer. Buffer-replace is not something we want when you edit your file. That's why you only see the changes you made. If you  just open a `example.txt` file and write it, and hit undo `u`, you should see the exact behavior. Here are the problems we had, which we fixed:

http://stackoverflow.com/questions/12741977/prevent-vim-from-updating-its-undo-tree
http://stackoverflow.com/questions/18532692/golang-formatter-and-vim-how-to-destroy-history-record

I don't want to change it if you mean that :)

**Comment by phemmer** [comment]
> If you just open a example.txt file and write it, and hit undo u, you should see the exact behavior.

This is a bad comparison. When you write `example.txt`, vim isn't going to change your document before the save.

**Comment by fatih** [comment]
If you change it and hit `:w` and hit `u` you get the same behavior in vim-go. Vim-go only saves when `g:go_fmt_autosave` is enabled (which is by default). You can always disable it thought. So once you disable it, it's the same as vim. If you enable it, your text will be formatted and undo's are working well. Am I missing something here?

**Comment by fatih** [comment]
Any response on this?

**Comment by phemmer** [comment]
I'm maintaining my own fork of the code. Will close.
