### ISSUE TITLE
Allow terminating GoImports

### ISSUE THREAD

**Issue by faxal** [fatih/vim-go#431]
I don't know if this is possible, since I have very limited knowledge of vim scripting. 

Is it possible to allow termination of a running `:GoImports`, as sometimes the underlying `goimports` tool takes a lot of time.

Or allow `:GoImports` to take an optional argument to kill after `n` seconds.

**Comment by fatih** [comment]
Hi @faxal 

Unfortunately not. There is already some speed up improvements. And some go devs are alrady working on further improving goimports. Actually, that is the reason `:GoImports` exists. Because you hook gofmt to your auto hook and call `:GoImports` only if you need it (to populate the imports).
