### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by John-Appleseed** [fatih/vim-go#435]
I want to use [Sourcegraph](https://sourcegraph.com) for vim-go code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/fatih/vim-go. (It should only take 30 seconds.)

Thank you!

**Comment by fatih** [comment]
Thanks but @sourcegraph want's to have `commit access` which enables them to have `write access` which I don't know why they need it. Second, once I want to enable, Sourcegraph want's to have access to all organizations, which I can't give because It also contains my work account/organization. Thanks.
