### ISSUE TITLE
Please specify a license for this project

### ISSUE THREAD

**Issue by hillu** [fatih/vim-go#443]
Hi,

please clarify what terms this project is licensed under.

Several files which seem to have come from the golang-go sources carry a notice like "Copyright 20xx The Go Authors. All rights reserved. Use of this source code is governed by a BSD-style license that can be found in the LICENSE file." -- but there is no such file.in the repository. Most of the source files don't have any copyright notice and no license attached to them.

Debian is looking for a replacement for the `vim-syntax-go` package which previously was built from the `golang-go` sources and `vim-go` looks like the obvious candidate. This can't happen if the license is not clear, however.

Cheers,
-Hilko

**Comment by fatih** [comment]
Hi Hilko

I'm always using the MIT license for all my open source projects. However the initial code from vim-go is based from go's source repo, which is based on BSD-style license.

I don't know much about licenses, all I know is that I need to be careful and also respect the previous license. I need to investigate it and also get some consulting so I can give you a better answer, because even If I'm in favor of MIT license, it might not compatible or even not suited because of the license which  was initially set via the go team.

**Comment by hillu** [comment]
Fatih,

If I interpret http://www.dwheeler.com/essays/floss-license-slide.html correctly, it should not be a problem to put everything under a 3-clause BSD license, given that the original code was published under such a license.

Cheers,
-Hilko

**Comment by fatih** [comment]
Hi Hilko,

That makes totally sense. The 3-clause BSD license is a good one and I support it. However I just want to be sure to not make any mistakes here. I've asked it in golang-nuts to the original authors. If everything is ok, I'll add the LICENSE file and mark it as 3-clause BSD license.

**Comment by fatih** [comment]
Hi Hilko,

I've added the license: https://github.com/fatih/vim-go/commit/cc52dd3d52737a215bf634e1da563938a3f8b483

I'll close this issue, let me know if there is something to be done or changed. Thanks for bringing this up.
