### ISSUE TITLE
Don't run `go version` on every startup

### ISSUE THREAD

**Issue by eapache** [fatih/vim-go#458]
I was profiling my vim startup recently; a non-trivial amount of time (~50ms) was taken by this plugin running `go version`. Since the result of this changes so infrequently, it would be a good optimization if there was some way to cache this value or something.

Also: the file I was profiling wasn't even a go file. If there is a way to delay the `go version` run until the first go file is actually loaded that might also be useful.

**Comment by fatih** [comment]
Hi @eapache . This is already cached and it's only used once during the startup. After it it's never get called. I don't know how we can cache beside putting a file somewhere having it, which again makes things complicated.  The `go version` calling was added two weeks ago:

https://github.com/fatih/vim-go/commit/91f8ed01d8fd44dab7fd3b5a8c7e60406b0d8419

This is going to be removed once 1.5 is out. This is not in autoload because the command `:GoInstallBinaries` can be called from everywhere (such as an empty scratch buffer)

**Comment by fatih** [comment]
Related issue why we have this: https://github.com/fatih/vim-go/pull/434

**Comment by eapache** [comment]
Ah, thanks for the context, not a big deal then, especially if it will go away once 1.5 is out.

**Comment by fatih** [comment]
Yeap :) I'm not closing this so we don't forget it. Thanks for the report.
