### ISSUE TITLE
go_fmt_autosave is slow

### ISSUE THREAD

**Issue by zeast** [fatih/vim-go#459]
" delete any leftover before we replace the whole file. Suppose the
                                    " file had 20 lines, but new output has 10 lines, only 1-10 are
                                    " replaced with setline, remaining lines 11-20 won't get touched. So
                                    " remove them.
    1              0.000004         if line('$') > len(splitted)
                                        execute len(splitted) .',$delete'
                                    endif
                            
                                    " setline iterates over the list and replaces each line
    1             13.487943         call setline(1, splitted)

I let g:go_fmt_autosave = 1 in my vimrc, then the save is very slow.
run  `!goimports -w=true %`  in vim is fast.  if you can use this instead of setline? or it's only happened on my computer

**Comment by fatih** [comment]
Did you read the code? There is a reason why don't just use goimports or gofmt, because it might return an error and we don't want to replace your file with the error content right? It should be actually very fast, how long is your file?

**Comment by zeast** [comment]
Thanks for your explanation. The file has about 1200 lines.

**Comment by fatih** [comment]
@zeast Can you give more detail how you profiled it? Just want to be sure I'm on the same page when I try to debug the code with an example 1200 line long file.

**Comment by zeast** [comment]
@fatih 
Yesterday, I write a function T like this
```
function! T()
    let splitted = ['package main','','import (','    "fmt"',')',' ','func main() {','','}','func f(){' , '    fmt.Println("--------")',  '    fmt.Println("--------")',  '    fmt.Println("--------")',  '    fmt.Println("--------")',  '    fmt.Println("--------")',  '    fmt.Println("--------")',  '    fmt.Println("--------")',  '    fmt.Println("--------")',  '    fmt.Println("--------")',  '    fmt.Println("--------")' ,  '    fmt.Println("--------")' ,  '    fmt.Println("--------")' ,  '    fmt.Println("--------")' ,  '    fmt.Println("--------")' ,  '    fmt.Println("--------")' ,  '    fmt.Println("--------")' ,  '    fmt.Println("--------")' ,  '    fmt.Println("--------")' ,  '    fmt.Println("--------")' ,  '    fmt.Println("--------")' ,  '    fmt.Println("--------")' ,  '    fmt.Println("--------")' ,  '    fmt.Println("--------")' ,  '    fmt.Println("--------")' ,  '    fmt.Println("--------")' ,  '    fmt.Println("--------")' ,  '    fmt.Println("--------")' ,  '    fmt.Println("--------")' ,  '    fmt.Println("--------")' ,  '    fmt.Println("--------")' ,  '    fmt.Println("--------")' ,  '    fmt.Println("--------")' ,  '    fmt.Println("--------")' ,  '    fmt.Println("--------")' ,  '    fmt.Println("--------")' ,  '    fmt.Println("--------")' ,  '    fmt.Println("--------")' ]
    call setline(1, splitted)
endfunction
```
and the function T is slow, so I suspect other plugins because the function T is sort. Then I comment other plugins but no change. Today, I find maybe `fdm=syntax` is the culprit or conflict with other. I comment it, save is fast. But I don’t know why the profile point setline. 
I profiled follow http://stackoverflow.com/questions/12213597/how-to-see-which-plugins-are-making-vim-slow

example long file :
```
package main

import (
    "fmt"
)

func main() {

}

func f() {
    fmt.Println("--------")
    // a lot of fmt.Println("--------")
    fmt.Println("--------")
}
```
test vimrc :
```
set fdm=syntax

let mapleader=","

set shell=/bin/bash

filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'gmarik/Vundle.vim'

Plugin 'fatih/vim-go'
  au FileType go nmap <Leader>gd <Plug>(go-doc)
  au FileType go nmap <Leader>s <Plug>(go-implements)
  au FileType go nmap <Leader>i <Plug>(go-info)
  au FileType go nmap <Leader>e <Plug>(go-rename)
  let g:go_highlight_functions = 1
  let g:go_highlight_methods = 1
  let g:go_highlight_structs = 1
  let g:go_highlight_operators = 1
  let g:go_fmt_autosave = 1
  let g:go_highlight_build_constraints = 1
  let g:go_fmt_command = "goimports"
call vundle#end()
"filetype plugin indent on
syntax on

function! T()
    let splitted = ['package main','','import (','    "fmt"',')',' ','func main() {','','}','func f(){' , '    fmt.Println("--------")',  '    fmt.Println("--------")',  '    fmt.Println("--------")',  '    fmt.Println("--------")',  '    fmt.Println("--------")',  '    fmt.Println("--------")',  '    fmt.Println("--------")',  '    fmt.Println("--------")',  '    fmt.Println("--------")',  '    fmt.Println("--------")' ,  '    fmt.Println("--------")' ,  '    fmt.Println("--------")' ,  '    fmt.Println("--------")' ,  '    fmt.Println("--------")' ,  '    fmt.Println("--------")' ,  '    fmt.Println("--------")' ,  '    fmt.Println("--------")' ,  '    fmt.Println("--------")' ,  '    fmt.Println("--------")' ,  '    fmt.Println("--------")' ,  '    fmt.Println("--------")' ,  '    fmt.Println("--------")' ,  '    fmt.Println("--------")' ,  '    fmt.Println("--------")' ,  '    fmt.Println("--------")' ,  '    fmt.Println("--------")' ,  '    fmt.Println("--------")' ,  '    fmt.Println("--------")' ,  '    fmt.Println("--------")' ,  '    fmt.Println("--------")' ,  '    fmt.Println("--------")' ,  '    fmt.Println("--------")' ,  '    fmt.Println("--------")' ,  '    fmt.Println("--------")' ,  '    fmt.Println("--------")' ,  '    fmt.Println("--------")' ,  '    fmt.Println("--------")' ]
    call setline(1, splitted)
endfunction
```

**Comment by fatih** [comment]
@zeast Thanks a lot for the detailed information. Let me look at this later. Maybe we can improve it via `append` instead of using `setline`. This could probably improve the situation.

**Comment by fatih** [comment]
Hi @zeast 

So I've profiled myself on a 1000 line long file and the running time of `go#fmt#Format()` is;

```
FUNCTION  go#fmt#Format()
Called 1 time
Total time:   0.066188
 Self time:   0.004678
```

The most time it spent was only while it was executing:

```
1   0.056948   0.000196     let out = system(command . " " . l:tmpname)
```

Where `splitline` was very low:

``` 
1              0.000760         call setline(1, splitted)
```

It' seems it's heavily dependent on the machine it's running. I have MacBook Pro 15 (Late 2013) with 8 cores, which might the reason it's executing very fast.  I mean in my case the bottleneck is not at all at setline. Can you please profile with the following command: 

```
vim --cmd 'profile start profile.log' --cmd 'profile! func *' -u ~/.test-vimrc your-1000-line-long-file.go
```

and then simply execute `:wq` (which will :GoFmt once and then exit). It should populate a `profile.log` file. Please upload the file to gist or something similar so we can check it. 

Thanks

**Comment by zeast** [comment]
@fatih 
I find if I use ``` -u ~/test_vimrc```, I will get error message
```
Error detected while processing /Users/zhuliang/.vim/bundle/Vundle.vim/autoload/vundle.vim:
line    9:
E10: \ should be followed by /, ? or &
```

So I backup ~/.vimrc and move test_vimrc to ~/.vimrc and use command
` vim --cmd 'profile start profile.log' --cmd 'profile! func *’ t.go `

I use an iMac of 2011, the cpu info is
``` 
machdep.cpu.brand_string: Intel(R) Core(TM) i5-2500S CPU @ 2.70GHz
achdep.cpu.core_count: 4
```
gist: https://gist.github.com/zeast/99f3f6d650e4e04b1ec9

**Comment by fatih** [comment]
Thanks @zeast. Which Vim version are you using? It's unbelievable how much different the profile log is for you and for me. Especially the `setline` call. For me it's not taking that much, but for you it's really bad. I'm looking into recent Vim patches, I wonder if this is something that is improved later.

**Comment by zeast** [comment]
@fatih 
I’m very puzzled. Yesterday I reinstall the system of a MacBook Pro 2014.  Today, when I receive you message, I test at the MacBook, nothing changed.

I install vim from https://github.com/vim/vim
config command: `./configure --with-features=huge --enable-multibyte --enable-rubyinterp --enable-pythoninterp --enable-perlinterp --enable-luainterp  --enable-cscope --with-tlib=ncurses --prefix=/usr/local`
vim version is here: https://gist.github.com/zeast/23eeeadc4a2d321103e9

**Comment by fatih** [comment]
I'm on this. I have also tested in write saving via `-w`, but this option also has it quirks, like not obeying history, breaking the history and removing the syntax highlighting. Another call would be using `append`, but append is breaking the layout. So I'm still looking at this, probably will be looking at it full time on my weekend. This is one of Vim's and VimL shortcomings which is full of side effects, random changes due the huge changes and complex internal system. I hate it.

**Comment by zeast** [comment]
@fatih 
Thank you very much for you attention. I think vim is complicated too. In fact I remove ` fdm=syntax` from my vimrc and it’s work fine! (I don't know why) I hope this can help you. Vim-go is a very useful plugin when I coding by golang. If you need test reply this comment and I will see it.

**Comment by fatih** [comment]
I've asked a detailed question here:

http://stackoverflow.com/questions/31356643/prevent-cursor-jumping-to-bottom-when-the-buffer-is-replaced

Note that I have already two solutions (see above question) which works fine, however they both suffer from this problem:

http://d.pr/i/1buDZ

I hope we can find a proper solution for it, meanwhile I'm still looking at it.

**Comment by fatih** [comment]
I've also implemented an experimental mode with the `-w` flag (So we now have three different options (four with the current one) which formats the buffer) https://github.com/fatih/vim-go/commit/01578fd8632870f8285266b93c1e219df19c4002

This also has some quirks though:

1. If you hit `:w`, `BufWritePre` will be triggered, but inside the function the file will be changed via gofmt. When the function ends the write process of Vim will be triggered too. So we have two write operations, one via gofmt and one via Vim. This causes Vim to prompt a question and it's just annoying. I reload the file however so it doesn't ask for me, but...

2. Because we reload the file, Vim disables the syntax highlighting of the file. We need to reload the syntax again, however in my environment when I reload the syntax again it breaks the statusline. I'm not sure if this happens for others but it's just annoying.

Anyway, I'm not saying we should use this, this is just another alternative I've pushed to the [fmt-in-write](https://github.com/fatih/vim-go/tree/fmt-in-write) branch. Let's see if we can find a proper solution to all these problems.

**Comment by guns** [comment]
Hi @fatih,

I had the same problem as @zeast, and also profiled vim-go to discover that
`setline(1, list)` was very slow for me.

Unfortunately, I didn't find this thread until I spent a couple of hours
debugging and digging around in the Vim source. That said, the reason
[f_setline](https://github.com/vim/vim/blob/54e9a62ad6106b9db63cfbbd84efec1ce82c69d0/src/eval.c#L17021-L17095)
blows up in running time when `foldmethod=syntax` is because setline becomes
~O(n²) when folds are enabled.

In particular:

https://github.com/vim/vim/blob/54e9a62ad6106b9db63cfbbd84efec1ce82c69d0/src/eval.c#L17074

```c
changed_bytes(lnum, 0);
```

is called for every line changed by setline. `changed_bytes`, in turn,
primarily marks the parts of windows that need a redraw, but it also updates
folds:

https://github.com/vim/vim/blob/54e9a62ad6106b9db63cfbbd84efec1ce82c69d0/src/misc1.c#L3103-L3196

If you look closely and follow some of the function calls, you may notice that
there are a lot of search loops. Since these inner loops are called for every
line touched by setline, the running time explodes.

Humorously, since the folds are updated `FOR_ALL_TAB_WINDOWS`, the time taken
for a `:GoFmt` rises linearly with the number of windows that have that buffer
open. For instance, I have a 650 line file that takes 2 seconds to execute
`:GoImports`. If I split the window and run it again, it takes 4 seconds, and
if I split the window again it takes 6 seconds.

I think using the `-w` flag of gofmt is definitely going to be easier than
dealing with this issue from within vim. We do the same thing in the Clojure
version of `goimports`, and it works well:

https://github.com/technomancy/slamhound/blob/master/src/slam/hound.clj#L45-L68

I've submitted a patch to improve on the fmt-in-write branch, #492.

**Comment by fatih** [comment]
@zeast @luan @gbbr could you please use #492 and report back? I've just tested and it's an improvement of my current https://github.com/fatih/vim-go/tree/fmt-in-write branch. @guns did here a great job and I really thank him, nice job :+1:

**Comment by zeast** [comment]
@fatih 
The branch work well. And I found a different point is when I save file, it's show two filename now.
![image](https://cloud.githubusercontent.com/assets/9344800/8868958/204e9c20-3211-11e5-93a8-67bc33fca698.png)

**Comment by fatih** [comment]
@zeast this one is weird, there should be only file after you save something, how is it you see duplicates in the same folder?

**Comment by zeast** [comment]
@fatih 
What's the value of `shortmess` in you vimrc?
I use branch `fmt-in-write` and  `set shortmess=Ia` in my vimrc,  It's well be two filename.
If I comment  `set shortmess=Ia`. The filename is ok, but statusline well be change.

**Comment by guns** [comment]
@zeast 

I see, reloading the buffer is causing an extra message to appear, which does not happen if you have `o` in your `'shortmess'`.

The solution is to use `silent` when reloading the buffer.

I squashed and pushed a fix for that. Could you please try it now?

**Comment by fatih** [comment]
The fix is merged to master. Please pull and test it. If it is still slow, please attach a profile log too, so we can debug it. Thanks.
