### ISSUE TITLE
GoImports undoable

### ISSUE THREAD

**Issue by eatonphil** [fatih/vim-go#481]
It would be awesome if you could undo a GoImports deletion. I am always accidentally saving before I add a reference to a package I just added. I have to retype it instead of just hitting `u`.

**Comment by fatih** [comment]
Hi @eatonphil 

Thanks for the idea, though this is something out of control and vim-go doesn't track any state between your previously formatted code and the latter one. What you could do is using `gofmt` command and call `:GoImports` whenever you feel it's safe. Otherwise just hit `u`, which is way simpler than tracking the state. Thanks.
