### ISSUE TITLE
gocode and godep doesn't work together

### ISSUE THREAD

**Issue by YannMoisan** [fatih/vim-go#531]
I am using YCM, installing with this option --gocode-completer.

After having started Vim, I see the gocode daemon :

```
$ ps -ef | grep gocode
  501 53255     1   0  4:36PM ??         0:00.03 /Users/yamo/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/completers/go/../../../third_party/gocode/gocode -s -sock unix -addr localhost:37373
```

Completion works well on a built-ins (like fmt) but not on a dependency in GoDeps.

gocode displays the following message : Gocode returned empty JSON response

Nevertheless, godep seems have been correctly detected
`:GoPath` displays `/Users/yamo/Projects/.go/src/github.com/YannMoisan/openshift-skeleton/Godeps/_workspace:/Users/yamo/Projects/.go/vendor/:/Users/yamo/Projects/.go`

Any idea to fix that ?

**Comment by fatih** [comment]
Hi @YannMoisan 

Unfortunately vim-go is only compatible with plain YCM. If you use the completer within YCM I don't have much to say. vim-go is only fully compatible with gocode. Anything else is just optional features. For example if you install YCM in a normal way, you should directly get autocompletion, otherwise completion just is triggered with `C-X C-O` shortcuts. What happens if you do it that way?

Also please reinstall gocode again. As I know there is no internal support for gocode, vim-go tries to pass the path to gocode so it goes and pick them up. However for every package you want to autocomplete you need them `go install` before. If it's not installed gocode will return nothing. So please first install them either via `:GoInstall` from within vim or from terminal just do `go install`. Thanks.
