### ISSUE TITLE
vim is more and more slow each time I save (:w)

### ISSUE THREAD

**Issue by codeur4** [fatih/vim-go#546]
Vim is more and more slow each time I save (:w) until 10 min after 4 or 5 save.
I use *gvim* on windows.
I find that [http://stackoverflow.com/questions/12213597/how-to-see-which-plugins-are-making-vim-slow]
(http://stackoverflow.com/questions/12213597/how-to-see-which-plugins-are-making-vim-slow)
but when I run :version, it indicates me **profile** features isn't included.
I have clean all plugin to see if problem come from them, but nothing changed.
Please help.

**Comment by isacikgoz** [comment]
Hello @codeur4 

You can start your vim with `vim --startuptime ~/vim.log` if you are in windows `--startuptime C:\some\where\vim.log` <- this will help you to profile your vim configuration and you can see which plug-ins create bottlenecks.

Also, you can use vim in debug mode with `vim -D` and see what is happening after you type `:w` command. I recommend you to profile your vim at first.

Anyway, this issue is not seems to be related with `vim-go` plug-in.

**Comment by codeur4** [comment]
I have no vim.log file in any of my repertories. I don't know how enable/install profile.
But anyway, I found the solution, I delete this line in my vimrc file : 
`autocmd BufWritePost .vimrc,_vimrc source $MYVIMRC`
I found the solution by typing `set verbose=9` bofore save. Now it s working.

**Comment by isacikgoz** [comment]
Actually you create the `vim.log` file with `vim --startuptime ~/vim.log` option. It is not created automatically. It is better to find defect rather than a workaround.

**Comment by codeur4** [comment]
From where you execute `vim --startuptime ~/vim.log` ?
![startuptime](https://cloud.githubusercontent.com/assets/10487632/10106681/5eb1e5d6-63b6-11e5-873b-fcd60b3876a5.jpg)

**Comment by isacikgoz** [comment]
Actually `~/vim.log` is for unix systems, in your case you should type: `C:\somewhere\vim.log`

**Comment by HaleTom** [comment]
Look in the answer:
http://stackoverflow.com/questions/18024842/vimrc-file-takes-longer-and-longer-to-reload
in particular, it's, `augroup` to check out.
