### ISSUE TITLE
go-dev-vertical switch to existing open split

### ISSUE THREAD

**Issue by tgrosinger** [fatih/vim-go#570]
**Repro Steps**

1. Open a file, use `go-def-vertical` to open a referenced function in another file
2. In new split that opened, use `go-def-vertical` to open a reference in the same file

**Expected**

Move to the new location within the same vertical split

**Actual**

Opens a third vertical split with the same file as the second

**Additional Notes**

I have tried setting `switchbuf=useopen` however it seemed to have no effect.

**Comment by fatih** [comment]
Hi @tgrosinger 

This is expected, because you explicitly want to jump in the same file and want to open a vertical file. Sometimes you have a very long file, say over 600 lines. The definition you want to jump might be at the bottom and opening it on a new vertical window,even although it's in the same file is a preferred action. You are now able to see both definitions side by side.

Pleas use `gd` which jumps to the definition directly instead of opening any new split.

**Comment by tgrosinger** [comment]
Thank you, I will use `gd` to open in the same split, and `,gd` to open in another split. One more use-case though. 

If I have a.go and b.go open in splits next to each other, a.go focused and use `GoDef` on a reference that should open in b.go, how can I move to the correct location in my already open b.go?

**Comment by fatih** [comment]
> If I have a.go and b.go open in splits next to each other, a.go focused and use GoDef on a reference that should open in b.go, how can I move to the correct location in my already open b.go?

We don't have this feature right now. This might be something we could add as feature though. godef opens a buffer directly. What it could do is look for an existing one and then use it to jump. I think it could be fairly easy or a little difficult. I don't know the details.

**Comment by tgrosinger** [comment]
I think that could be a very popular feature. I know I certainly would enjoy it.

I don't know where in the code this is implemented, but Unite has this exact feature when opening new files. Here are the relevant docs: https://github.com/Shougo/unite.vim/blob/master/doc/unite.txt#L2904-L2905
