### ISSUE TITLE
How to turn-off a vim-go for a while?

### ISSUE THREAD

**Issue by timfayz** [fatih/vim-go#587]
Today I've installed vim-go using vim-plug package manager. I'm not experienced user in vim (use it less than 1 week). So the question is how can I disable/switch-off vim-go totaly? I don't know maybe there are ways to do it using vim-plug, but I didn't find information about it.

**Comment by fatih** [comment]
Just comment it out from your plugging manager. Closing because this is not vim-go related. Thanks

**Comment by timfayz** [comment]
Good, thank you!)

**Comment by timfayz** [comment]
In order not to pollute the issue tracker - could you explain how vim-go and YCM related to each other? I'm really new to vim so I don't imagine how YCM and your plugin do not overlap. How vim-go and YCM work together without interfering to each other? It would be great if you make things a little bit clearer to me)

**Comment by casimir** [comment]
@timfayz for vim-plug you can use an [option to lazy load plugin](https://github.com/junegunn/vim-plug#on-demand-loading-of-plugins). For exemple if you want the plugin loaded for `*.go` files only: 
```
Plug 'fatih/vim-go', {'for': 'go'}
```

As for YCM, it now provides a semantic completer when compiled with `--gocode-completer` (or something like that), meaning it handle autocompletion without the help of vim-go. If not compiled with this option it will fallback to the current `omnifunc` (see `:h omnifunc` for more details) and thus using the one provided by vim-go.

I tried to be concise because it's not really the place to talk about that. Hope this help though.
If you want to learn more about all of these things you could look at plugins sources and issues, they are mostly hosted on Github.

See also:
http://vim.wikia.com/wiki/Omni_completion
https://github.com/Valloric/YouCompleteMe#quick-feature-summary

**Comment by timfayz** [comment]
> If not compiled with this option it will fallback to the current omnifunc (see :h omnifunc for more details) and thus using the one provided by vim-go.

If I get you right, if I omit `--gocode-completer` flag during the YCM installation vim-go (through `omnifunc`) will be used instead? By the way, do you use YCM personally?

**Comment by casimir** [comment]
YCM without its completes is just a fuzzy matcher for possible completions. So this is more like `vim-go (querying gocode) → YCM listing → YCM completion` vs `ycmd (wrapping gocode) → YCM listing → YCM completion`.

I use YCM (with its go completer) and vim-go together every day (thank you so much @fatih BTW).

**Comment by timfayz** [comment]
Good! Things become clearer :) Could you explain the differences b/w these approaches in more details: `vim-go (querying gocode) → ..` and `ycmd (wrapping gocode) → ..`?

**Comment by casimir** [comment]
You really should look at YCM's documentation, it's all explained in the README. Very shortly gocode provide a list of possible identifiers while ycmd provide a list a symbols (identifier + type + doc? + ...)

**Comment by timfayz** [comment]
Ok, got it. I need a little time to sort it out) Thank you)
