### ISSUE TITLE
question: using GoMetalinter as replacement for Syntastic

### ISSUE THREAD

**Issue by svanharmelen** [fatih/vim-go#616]
Is there a way to use GoMetalinter on save, more or less in the way I can use Syntastic?

Thanks!

**Comment by fatih** [comment]
Hi @svanharmelen 

Unfortunately right now we don't have that kind of feature. I think I'm not going to add this to Vim too (because it would make it slow). However right now I'm working on Neovim integration and I'm going to make the linters all async. Please check the integration here: https://github.com/fatih/vim-go/pull/607

Also, even though we might add this, it'll not show the errors on the line number sidebar. Instead it only will show them via a quickfix window. But I'm thinking of adding it in the future (showing the errors on the linenumber sidebar).

Hope this answers your question. If not please let me know.

**Comment by svanharmelen** [comment]
Sounds good! And I'm already using the `nvim` branch (worked a full day on it today and looks good!) :wink: Thx!

**Comment by webhat** [comment]
[gometalinter](https://github.com/alecthomas/gometalinter) is supported by [syntastic](https://github.com/scrooloose/syntastic) see
https://github.com/scrooloose/syntastic/wiki/Go:---gometalinter
