### ISSUE TITLE
godef in vim-go is too slow

### ISSUE THREAD

**Issue by hongchaodeng** [fatih/vim-go#634]
Compared to Atom, Sublime plugins, godef in vim-go is too slow. This is especially obvious on large projects with 8700+ files.
Is there any plan to improve it?

**Comment by fatih** [comment]
Compared how? Please provide numbers to back up this, as all the editors using the same command line tool. If not please open the issue on https://github.com/rogpeppe/godef. Otherwise godef is pretty fast and there is not much we can do (vim-go just opens the file using the result of godef, there is no intermediate work). Thanks
