### ISSUE TITLE
about shellescape() in vim-go

### ISSUE THREAD

**Issue by shoulinwang** [fatih/vim-go#662]
Because the output of the shellescape() controlled by &shellslash in windows. when &shellslash=1,  it will lead :GoRun failure.

Recommended to use function like gocodeShellescape() in 'autoload/go/complete.vim'.

```vim
:set ssl
:GoRun %
```
```txt
C:\Windows\system32\cmd.exe /c (go run 'c:\GoLang\src\golang-book\chapter2\main.go')
go run: no go files listed
shell returned 1
Hit any key to close this window...
```
```vim
:set nossl
:GoRun %
```
```txt
C:\Windows\system32\cmd.exe /c (go run ^"c:\GoLang\src\golang-book\chapter2\main.go^")
Hello World
Hit any key to close this window...
```

**Comment by fatih** [comment]
Hi @shoulinwang. In your example the file names are the same, they both use backslashes. Are you sure it changes something ?

**Comment by fatih** [comment]
Btw we have custom function already for windows, which uses backslash automatically, checkout out the autoload/go/tool.vim file for the function `go#tool#Files()`

**Comment by shoulinwang** [comment]
The different points in the example are 'and"

**Comment by fatih** [comment]
I don't have any ways of testing it to produce a fix. All I can say is that `go#tool#Files()` is using `"` instead of `'` if it's Windows. So we already use `"`. The error might be caused by another function which uses shellescape. I've modified it so it uses your fix, can you try it wit this PR: https://github.com/fatih/vim-go/pull/690 as I said I don't have any way to test it.
