### ISSUE TITLE
close location list if initiating buffer is closed

### ISSUE THREAD

**Issue by nothingelsematters7** [fatih/vim-go#669]
When editing a buffer and the location list is opened, and then the original buffer is closed, the location list remains open. I think the location list should also close if the initiating buffer is closed.

Cloned from here: https://github.com/scrooloose/syntastic/issues/123
Example fix for Syntastic, may be helpful here too: https://github.com/scrooloose/syntastic/pull/126/files

**Comment by fatih** [comment]
Hi @nothingelsematters7 

It's not possible anymore to do it that way. That commit is old and causing Vim to print errors. Here is an updated commit which improved it, but also increased the code complexity: https://github.com/scrooloose/syntastic/pull/256 

So we need to a lot of work to make it work with vim-go. So because of my limited time, I'm letting this open and come back later in the future for tackling it. Thanks for opening the issue.

**Comment by nhooyr** [comment]
There are still corner cases with syntactic, https://github.com/scrooloose/syntastic/issues/626

**Comment by fatih** [comment]
I'm closing this as there is no easy way to do this. And because we have many other things before we even can tackle something like this, the priority is very low and probably we're not going to handle this issue for a very long time. Thanks for opening though. If you have any other comments or new features to improve the situation feel free to open another issue.
