### ISSUE TITLE
Text object functions: support the inner operator

### ISSUE THREAD

**Issue by tbruyelle** [fatih/vim-go#770]
### Expected behavior

If I type `diw` it deletes the whole word, whereas the cursor position inside the word. So I expect `di]]` or `di[[` to delete the whole function.

### Actual behavior

`di]]` or `di[[` does nothing.

#### vim version: 
7.4
#### vim-go version:
1.5
#### go version:
1.6

**Comment by fatih** [comment]
`[[` is a `text object motion`, whereas `if` is a `text object selection`. They are different. If you want to delete/yank/etc.. any kind of selection you have to use `if` and `af`. `w` is different that it's both a `text object motion` (you can move with it) and there is a seperate text object selection called: `iw`. Even though people think that there is only one single `w` that does it, they are different. 

As you see it's actually the same, we just use `]]`, `[[`, `if` and `af` for function declarations, and there is `w`, `b`, `iw` and `aw` for words. Does it make sense? The problem is that `f` is already used in Vim, that's why we're using `[[` and `]]`.
