### ISSUE TITLE
Calling :GoCoverage on a buffer containing a test file empties the buffer

### ISSUE THREAD

**Issue by peterhellberg** [fatih/vim-go#789]
### Actual behavior

When calling :GoCoverage on a buffer containing a test file it (sometimes) empties the buffer.
It also seem to interfere with `vim-gitgutter` since it clears all colors in the gutter.

### Expected behavior

To do nothing with the buffer containing a test file.

### Steps to reproduce:

1. Create test file containing `package minimal`
2. Call :GoCoverage
3. See the buffer emptied

### Configuration

* vim version: NVIM v0.1.3-384-g47d44e0
* vim-go version: a4f44db
* go version: 1.6

I disabled all plugins apart from vim-go, Vundle and my theme.

**Comment by fatih** [comment]
@peterhellberg is there another file called `minimal.go` next to `minimal_test.go`? You should actually call `:GoCoverage` on a non test file, but I've added a case where you could run it on a test file, and it would open the non test file. Seems like you don't have it?

**Comment by peterhellberg** [comment]
This also happens when I have minimal.go and minimal_test.go in two (split) buffers.

**Comment by peterhellberg** [comment]
Also, it seems that the coverage report is only run on buffers I’ve actively "visited" with my cursor. (If i open three files in vertical buffers and run :GoCoverage in the first buffer, then I only get a coverage report for that buffer… which is fine, but if I move to the second or third file they all get a coverage report)

**Comment by fatih** [comment]
@peterhellberg please say the problems one by one, it's getting confusing otherwise. I'm not sure what this issue is about now.

For your first comment, I've pushed a fix to master: https://github.com/fatih/vim-go/commit/5ce65295c297a99012756d63b3a6dae579cefc02

> This also happens when I have minimal.go and minimal_test.go in two (split) buffers.

I can't reproduce it unfortunately. Maybe it's due cwd problems. Can you add the following to your vim/nvim settings and try again:

```
" Enter automatically into the files directory
autocmd BufEnter * silent! lcd %:p:h
```

>Also, it seems that the coverage report is only run on buffers I’ve actively "visited" with my cursor. (If i open three files in vertical buffers and run :GoCoverage in the first buffer, then I only get a coverage report for that buffer… which is fine, but if I move to the second or third file they all get a coverage report)

We use `matchaddpos()` which is unfortunately `window` based. I'm explicitly not removing the highlighting because it might be useful to implement the actually test based on it. That's why `:GoCoverage` is a toggle. If I find a better solution I implement, for now you have to open the view after you call `:GoCoverage`.

**Comment by peterhellberg** [comment]
Thank you, and sorry for any confusion I caused. Your fix seems to work just fine.
