### ISSUE TITLE
Is it possible to get offline package for GoInstallBinaries?

### ISSUE THREAD

**Issue by bon-ami** [fatih/vim-go#845]
I am from China, so I cannot visit Google. I failed to install many binaries. Is there an easy way or at least practical way to install offline? I know I can download different binaries manually but I do not know what should I do with and where to put them. (I have way to connect with Google, but vim cannot.)
I am using Ubuntu and installed "golang" only. I suppose installing more would help.
Thank you.

**Comment by fatih** [comment]
Hi @bon-ami 

I'm not sure how to deal with it. There is no offline binaries unfortunately, because there are multiple OS's and it's not worth to provide precompiled binaries of all binaries. Maybe in the future we might provide it, but for now it's not a priority. It's also not actually a vim-go problem. Can you please ask your question to `goland-dev` mailing list? 

Thanks
