### ISSUE TITLE
:GoCoverage does return SUCCESS if no test files exists

### ISSUE THREAD

**Issue by fatih** [fatih/vim-go#859]
It should either assume the coverage is `0` or we should echo an error that :GoCoverage can't be run because there is no test files.

**Comment by tsne** [comment]
Hi,

how about adding the `-o` flag to `go test` and check if a binary was created or not? If there are no test files, no binary will be created. In this case we can print a message in the `go#cmd#Test` function.
For the coverage it is basically the same. We could check if the profile file was written.

**Comment by fatih** [comment]
My fix is wrong, reverting :)

**Comment by fatih** [comment]
@tsne that sounds like a good plan to tackle. Or we just can check if there is any `_test.go` and abort  if there is any.

**Comment by fatih** [comment]
@tsne this is now fixed. We just check if there is any _test.go files and abort. Let me know if it doesn't work for you :)

**Comment by tsne** [comment]
Hi @fatih.

The fix works fine for me. Thank you.

**Comment by mrnugget** [comment]
I think this change breaks the expected behaviour when running `:GoTest ./...`. I often open Vim from the root directory of a project, in which several subdirectories are Go packages. Running `go test ./...` in the root runs every test in every subdirectory -- even if no test files exist in the root directory.

This change breaks the documented behaviour of `:GoTest` with `./...` as argument. It checks if there are test files in the current/root directory and doesn't run any tests if there are none. Running the subdirectory test files is impossible without a `*_test.go` file in the root directory.

**Comment by fatih** [comment]
@mrnugget good point. I'll change the check so it only covers `:GoCoverage`

**Comment by fatih** [comment]
@mrnugget This is now fixed in master. Thanks for the feedback.

**Comment by mrnugget** [comment]
@fatih Thanks so much, that was fast :)
