### ISSUE TITLE
Add support for gutentags

### ISSUE THREAD

**Issue by magicalbanana** [fatih/vim-go#934]
### Actual behavior
Currently we use Tagbar for to define the `ctags`.

### Expected behavior
Add support for [gutentags](https://github.com/ludovicchabant/vim-gutentags)

**Comment by bruschill** [comment]
I believe @magicalbanana is referring to [this issue](https://github.com/ludovicchabant/vim-gutentags/issues/25) in vim-gutentags.

After some _very_ high-level testing, I've found that if I have `go_metalinter_autosave = 1` and `go_metalinter_autosave_enabled = ['golint']` the issue goes away, so it seems to be related to having the `vet` linter included with the other autosave linters.

**Comment by fatih** [comment]
Why do we need to add it ?

**Comment by bruschill** [comment]
@fatih I don't believe gutentags support something that needs to be added, as much as there's a error that arises when `vet` is run and gutentags is updating tags.

Ultimately, I believe it comes down to preventing those kind of conflicts within vim-go, rather than adding support for another plugin.

**Comment by ludovicchabant** [comment]
I may just be some obscure bug in my code (I'm gutentags' author), in which case you don't have anything to do over here. That bug is tracked over at https://github.com/ludovicchabant/vim-gutentags/issues/25. Fingers crossed!

**Comment by fatih** [comment]
I'm closing this as I don't think we need to add support for this right now. Thanks.
